#ifndef ____I2C_h__
#define ____I2C_h__

/*======================================================================================================================*/

#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#include "Processes.h"

/*======================================================================================================================*/

#define I2C_PROC_NAME     (char *)"I2C     "     /* I2C process name*/

/*======================================================================================================================*/

/**
 * @brief The main I2C procedure reading the GPS coordinates from I2C port generated by the STM32 Board.                    
 *        In case of the compilation for PC version it generates the GPS coordinates itself because the PC doesn't have I2C.
 * 
 * @code
 * void I2CProc(ProcParams_s *ProcParams);
 * @code
 * 
 * @param Procparams The parameters given to process for usage containing the shared memory and semaphore between processea controlling flags and other optional possible parameters.
 */
void I2CProc(ProcParams_s *ProcParams);

/*======================================================================================================================*/


#endif  //  ____I2C_h__


