/*======================================================================================================================*/

#include "I2C.h"

#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>

#include "CommonData.h"
#include "Processes.h"

#include "Network.h"

#include "Configuration.h"

#ifdef BEAGLE_BONE
#include <linux/i2c-dev.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#else
#include <time.h>
#include "Israel_Shape.h"
#endif


/*======================================================================================================================*/

#define MAX_LONGIGUDE             (  35.0 + 40.0/60.0  )  /*  Israel Limit in degrees minutes seconds ( ˚ ' " )  */         /*  ±180˚  */    // (  180 )
#define MIN_LONGIGUDE             (  34.0 + 16.0/60.0  )  /*  Israel Limit in degrees minutes seconds ( ˚ ' " )  */         /*  ±180˚  */    // ( -180 )

#define MAX_LATITUDE              (  33.0 + 17.0/60.0  )  /*  Israel Limit in degrees minutes seconds ( ˚ ' " )  */         /*  ±90˚   */    // (  90  )
#define MIN_LATITUDE              (  29.0 + 29.0/60.0  )  /*  Israel Limit in degrees minutes seconds ( ˚ ' " )  */         /*  ±90˚   */    // ( -90  )

#define RESOLUTIONS                10000000000  

#define REG_PERIODE                10                     /*  Coordinates Regeneration Periode in seconds.       */         



/*======================================================================================================================*/

// void InitI2C();
// void DoI2C();
// void CloseI2C();


/*======================================================================================================================*/

/*
 * *************************************************************************************************************
 **          I2C Accessing Functions / Procedures
 * *************************************************************************************************************
 */

#ifdef BEAGLE_BONE
/*----------------------------------------------------------------------------------------------------------------------*/
/* Reads the data from the I2C device file.                                                                             */
void ReadI2C(int I2CDevFile, unsigned char buffer[], size_t size) 
 {
  bool StdErrNoPiping = isatty(STDERR_FILENO); /* Checking if the output is not redirected to any other program or file to decide if to use colors or not. */
  bool StdOutNoPiping = isatty(STDOUT_FILENO); /* Checking if the output is not redirected to any other program or file to decide if to use colors or not. */
  ssize_t result;
  char buf[50];

  result = read(I2CDevFile, buffer, size);
  if (result != (ssize_t)size) /* Fail. */
   {
    snprintf(buf, sizeof(buf), "%sFailed to read from the I2C bus%s", (StdErrNoPiping ? ResultColors[E_FAIL] : ""), (StdErrNoPiping ? TermColorsReset : ""));
    perror(buf);
   }
  else   /* Success. */
   {
    printf("%sWhere read %d bytes from I2C.%s\n\r", (StdOutNoPiping ? ResultColors[E_SUCCESS] : ""), result, (StdOutNoPiping ? TermColorsReset : ""));
   }
 }
#else
#endif

/*----------------------------------------------------------------------------------------------------------------------*/
/* The main I2C procedure reading the GPS coordinates from I2C port generated by the STM32 Board.                       */
/* In case of the compilation for PC version it generates the GPS coordinates itself because the PC doesn't have I2C.   */
void I2CProc(ProcParams_s *ProcParams)
 {
  bool StdErrNoPiping = isatty(STDERR_FILENO); /* Checking if the output is not redirected to any other program or file to decide if to use colors or not. */
  bool StdOutNoPiping = isatty(STDOUT_FILENO); /* Checking if the output is not redirected to any other program or file to decide if to use colors or not. */

  Customer_s CustomerData;
  NetQueue_s NetQueue = {0};
  size_t skipno = 0;
  bool Exit = false;
  char buf1[200], buf2[100], buf3[75];
#ifdef BEAGLE_BONE
  int const I2CAddr = I2C_ADDR;      /* Device address */
  char const *I2CPath = I2C_PATH;    /* Device path    */
  int I2CDevFile;
  ParkingData_s Parking;
  char buf[70];
#else
  UNUSED(StdErrNoPiping);
#endif

  printf("Starting I2C Task.\n\r");

#ifdef BEAGLE_BONE
  /* Open the I2C bus device file   */

  snprintf(buf, sizeof(buf), "Trying to open I2C device on port: %s...", I2CPath);
  LogEvent(&ProcParams->TskContShqs, MakeLogMessage(E_LOG_MESSAGE, ProcParams->ProcName, buf));
  printf("%s\n\r", buf);
  if((I2CDevFile = open(I2CPath, O_RDWR)) < 0) /* Failed to Open. */
   {
    snprintf(buf, sizeof(buf), "%sFailed to open the i2c bus. Recheck the port: %s.%s", (StdErrNoPiping ? ResultColors[E_FAIL] : ""), I2CPath, (StdErrNoPiping ? TermColorsReset : ""));
    perror(buf);
    snprintf(buf, sizeof(buf), "Failed to open the i2c bus on the port: %s.", I2CPath);
    LogEvent(&ProcParams->TskContShqs, MakeLogMessage(E_LOG_FAIL, ProcParams->ProcName, buf));
    Exit = true;
   }
  else  /* The device was opened successfully. */
   {
    printf("%sDevice was opened successrully on port: %s .%s\n\r", (StdOutNoPiping ? ResultColors[E_SUCCESS] : ""), I2CPath, (StdOutNoPiping ? TermColorsReset : ""));
    snprintf(buf, sizeof(buf), "The device on the port: %s was opened successfully.", I2CPath);
    LogEvent(&ProcParams->TskContShqs, MakeLogMessage(E_LOG_EVENT, ProcParams->ProcName, buf));
    if (ioctl(I2CDevFile, I2C_SLAVE, I2CAddr) < 0) /* Failed to configure. */
     {
      snprintf(buf, sizeof(buf), "%sFailed to acquire bus access and/or talk to slave%s", (StdErrNoPiping ? ResultColors[E_FAIL] : ""), (StdErrNoPiping ? TermColorsReset : ""));
      perror(buf);
      snprintf(buf, sizeof(buf), "Failed to configure the i2c bus on the port: %s.", I2CPath);
      LogEvent(&ProcParams->TskContShqs, MakeLogMessage(E_LOG_FAIL, ProcParams->ProcName, buf));
      Exit = true;
     }
    else /* Success in configuration. */
     {
      printf("%sThe device was configured successfully.%s\n\r", (StdOutNoPiping ? ResultColors[E_SUCCESS] : ""), (StdOutNoPiping ? TermColorsReset : ""));
      snprintf(buf, sizeof(buf), "The device on the port: %s was configured successfully.", I2CPath);
      LogEvent(&ProcParams->TskContShqs, MakeLogMessage(E_LOG_EVENT, ProcParams->ProcName, buf));
     }

   }

#else
  srand(time(NULL));
#endif

  
  
  strncpy(CustomerData.Customer_Name, GetClientName(), sizeof(CustomerData.Customer_Name) - 1);
  CustomerData.Vechicle_ID = GetVechicleID();
  
  InitNetQueue(&NetQueue.mq, QUEUE_SEND_E, ((TskContShmData_s*)ProcParams->TskContShms.p_shm)->NetQueueName);
  
  while((getppid() != 1) && (get_flag((TskContShmData_s*)ProcParams->TskContShms.p_shm, PROC_I2C_E) != true) && (Exit != true))
   {
    if(skipno++ >= REG_PERIODE)
     {
      skipno = 0;
#ifdef BEAGLE_BONE
      /* Reading random generated GPS coordingates from STM32 Board. */
      ReadI2C(I2CDevFile, (uint8_t *)&Parking, sizeof(Parking));
      CustomerData.Cords.Latitude  = Parking.ParkingCords.Latitude;
      CustomerData.Cords.Longitude = Parking.ParkingCords.Longitude;
#else

#define GEN_BY_ZONES 1

#if !defined(GEN_BY_ZONES) || (GEN_BY_ZONES == 0)

      /* Generating random GPS coordingates. */
      PointState_e Result;
      do
       {
         /* code */
         CustomerData.Cords.Longitude = ( fmod( RandGenLongLong() , ((MAX_LONGIGUDE - MIN_LONGIGUDE) * RESOLUTIONS) ) ) * 1.0 / RESOLUTIONS + MIN_LONGIGUDE;
         CustomerData.Cords.Latitude  = ( fmod( RandGenLongLong() , ((MAX_LATITUDE  - MIN_LATITUDE ) * RESOLUTIONS) ) ) * 1.0 / RESOLUTIONS + MIN_LATITUDE ;
         Result = PointInPoly(IsraelShape, NUM_IL_SHAPE_PNT, CustomerData.Cords);
       } 
      while (Result != INSIDE_E);

#else      
      const GPS_Cords_s GivatHaviva = {.Longitude = 35.021712, .Latitude = 32.457740};     
      const GPS_Cords_s GivatHen    = {.Longitude = 34.87660 , .Latitude = 32.16771 };     
      const GPS_Cords_s BneyBraq    = {.Longitude = 34.8402  , .Latitude = 32.0903  };     
      const GPS_Cords_s TelAviv     = {.Longitude = 34.77555 , .Latitude = 32.07841 };     
      const GPS_Cords_s Eilat       = {.Longitude = 34.9355  , .Latitude = 29.5434  };     
      const GPS_Cords_s RamatGan    = {.Longitude = 34.8227  , .Latitude = 32.0655  };     
      const GPS_Cords_s PetachTiqua = {.Longitude = 34.8798  , .Latitude = 32.0904  };     
      const GPS_Cords_s Herzlya     = {.Longitude = 34.82398 , .Latitude = 32.16867 };     
      const GPS_Cords_s Nahariyya   = {.Longitude = 35.10039 , .Latitude = 33.01059 };     
      const GPS_Cords_s Netanya     = {.Longitude = 34.86301 , .Latitude = 32.30890 };     

      const GPS_Cords_s Cities[] = { GivatHaviva, GivatHen, BneyBraq, TelAviv, Eilat, RamatGan, PetachTiqua, Herzlya, Nahariyya, Netanya };
      const size_t NumCitiesConsts = sizeof(Cities) / sizeof(Cities[0]);
      int r;
      r = rand();
      size_t CityToSelect = r % NumCitiesConsts;
      CustomerData.Cords = Cities[CityToSelect];
      // printf("The number of cities is: %ld\n\r", NumCitiesConsts);
      // printf("Generated number is: %ld\n\r", CityToSelect);
      // printf("%d mod %ld = %ld\n\r", r, NumCitiesConsts, CityToSelect);

      // CustomerData.Cords = TelAviv;

#endif

#endif

      CreateCordsFormatted(buf1, sizeof(buf1), CustomerData.Cords, StdOutNoPiping);
      CreateVehIDFormated(buf2, sizeof(buf2), CustomerData.Vechicle_ID, StdOutNoPiping);
      CreateNameFormated(buf3, sizeof(buf3), CustomerData.Customer_Name, StdOutNoPiping);
      printf("Customer name: %s Vehicle: %s\n\rThe generated cordinates are: %s\n\r", buf3, buf2, buf1);

      /* Senging coordingates to the network process. */
      SendMessageToNetwork(&NetQueue, &CustomerData, sizeof(CustomerData));
     }

    /* Making delay between sendings. */
    sleep(1);
   }
  CloseNetQueue(&NetQueue.mq, ((TskContShmData_s*)ProcParams->TskContShms.p_shm)->NetQueueName);

#ifdef BEAGLE_BONE
  close(I2CDevFile);
#else
#endif

  printf("Finishing I2C Task.\n\r");
 }


//  void InitI2C()
//   {

//   }

// void DoI2C()
//  {

//  }

// void CloseI2C()
//  {

//  }




 /*======================================================================================================================*/