#include"Vocobulary.hpp"



const std::string VocNames[NUM_VOC_PAIRS][VOC_PAIR_SIZE] = 	
  
 {
  //	name		latin name	
  {"נאות אפקה ב","Neot Afeka B"},
  {"רמת אביב ג","Ramat Aviv C"},
  {"(יפו ד' (גבעת התמרים","(Jaffa D.) (Giv'at al-Tamar)"},
  {"A'raa'ra Bedouins","A'raa'ra Bedouins"},
  {"Abu Issa Arab Village","Abu Issa Arab Village"},
  {"Al-Baka'a","Al-Baka'a"},
  {"Al-Hawakir","Al-Hawakir"},
  {"Al-Marah","Al-Marah"},
  {"Al-Zahra'","Al-Zahra'"},
  {"AlHilah","AlHilah"},
  {"Ali Gunaim Village","Ali Gunaim Village"},
  {"AlThaqara","AlThaqara"},
  {"AlZahear","AlZahear"},
  {"Amishav","Amishav"},
  {"Baqi Al Qasr","Baqi Al Qasr"},
  {"Birin","Birin"},
  {"Deir Musa village","Deir Musa village"},
  {"Em Hamoshavot hadasha","Em Hamoshavot hadasha"},
  {"Gat","Gat"},
  {"Gat city apron","Gat city apron"},
  {"Jewish Hamlet","Jewish Hamlet"},
  {"Jewish Hamlet","Jewish Hamlet"},
  {"Jordanian Police Station","Jordanian Police Station"},
  {"Mantiqat Shi'b al Batum","Mantiqat Shi'b al Batum"},
  {"Marah Saa'd","Marah Saa'd"},
  {"Marj Deeb - Kafrthulth","Marj Deeb - Kafrthulth"},
  {"Migdal Haemeq","Migdal Haemeq"},
  {"Muscat","Muscat"},
  {"Rustum","Rustum"},
  {"Saddet al-Tha'la","Saddet al-Tha'la"},
  {"Surif Old City","Surif Old City"},
  {"The Negev Camel Ranch","The Negev Camel Ranch"},
  {"Wadi Abu Hindi","Wadi Abu Hindi"},
  {"א-רוואלין","A-Ravalin"},
  {"א.ת. שילה","A.T. Shiloh"},
  {"אבו ג'ווייעד","Abu Jawaid"},
  {"אבו סנינא","Abu Sanina"},
  {"אבטליון","Avtalion"},
  {"אביאל","Aviel"},
  {"אביבי הרצליה","Avivi Herzliya"},
  {"אביבים","Avim"},
  {"אביגדור","Avigdor"},
  {"אביחיל","Avichail"},
  {"אביטל","Avital"},
  {"אביעזר","Abiezer"},
  {"אבירים","Avirim"},
  {"אבן יהודה","Even Yehuda"},
  {"אבן מנחם","Even Menachem"},
  {"אבן ספיר","Even Sapir"},
  {"אבן שמואל","Even Shmuel"},
  {"אבני איתן","Even Eitan"},
  {"אבני חפץ","Even Chefetz"},
  {"אבשלום","Absalom"},
  {"אגודת השומרים","Association of the Guardians"},
  {"אדורה","Adora"},
  {"אדירים","Adirim"},
  {"אדמה","Adama"},
  {"אדמית","Adamit"},
  {"אדרת","Aderet"},
  {"אובנת","Avnat"},
  {"אודים","Odim"},
  {"אודם","Odem"},
  {"אוהד","Ohad"},
  {"אומן","Omen"},
  {"אומץ","Ometz"},
  {"אוניברסיטת ת\"א","Tel Aviv University"},
  {"אופקים","Ofakim"},
  {"אור הגנוז","Or HaGanuz"},
  {"אור הנר","Or HaNer"},
  {"אור יהודה","Or Yehuda"},
  {"אור עקיבא","Or Akiva"},
  {"אורה","Ora"},
  {"אורות","Orot"},
  {"אורות","Orot"},
  {"אורטל","Ortal"},
  {"אורים","Urim"},
  {"אורנים","Oranim"},
  {"אורנית","Oranit"},
  {"אושה","Osha"},
  {"אזור","Azor"},
  {"אזור הבילויים","Entertainment Area"},
  {"אזור מלאכה","Craft Area"},
  {"אזור שדה דב","Sde Dov Area"},
  {"אזור תעסוקה - צומת חולון","Employment Area - Holon Junction"},
  {"אזור תעשייה כרמיאל","Carmiel Industrial Area"},
  {"אחוה","Ahva"},
  {"אחוזם","Ahuzam"},
  {"אחוזת ברק","Ahuzat Barak"},
  {"אחיה","Ahiah"},
  {"אחיהוד","Ahihud"},
  {"אחיטוב","Achitov"},
  {"אחיסמך","Ahismach"},
  {"אחיעזר","Ahi'ezer"},
  {"אי יונים","Yonim Island"},
  {"אי תמנון","Octopus Island"},
  {"איבי הנחל","Abi Hanahal"},
  {"איבים","Ibim"},
  {"איבתאן","Ibtan"},
  {"אייל","Ayel"},
  {"איילת השחר","Ayelet Hashachar"},
  {"איכסל","Iksal"},
  {"אילון","Eilon"},
  {"אילות","Eilot"},
  {"אילניה","Ilaniya"},
  {"אילת","Eilat"},
  {"אינתיצאר","Intitzar"},
  {"אירוס","Irus"},
  {"איתמר","Itamar"},
  {"איתן","Eitan"},
  {"איתנים","Eitanim"},
  {"אל עביד","El Abid"},
  {"אל-רום","El-Rom"},
  {"אלומה","Aluma"},
  {"אלומות","Alumot"},
  {"אלון","Alon"},
  {"אלון הגליל","Alon HaGalil"},
  {"אלון מורה","Elon Moreh"},
  {"אלון שבות","Alon Shvut"},
  {"אלוני אבא","Alonei Abba"},
  {"אלוני הבשן","Alonei HaBashan"},
  {"אלוני יצחק","Alonei Yitzhak"},
  {"אלוני שילה","Alonei Shilo"},
  {"אלונים","Alonei"},
  {"אלי עד","Eliad"},
  {"אליאב","Eliav"},
  {"אליכין","Elyakhin"},
  {"אליפז","Elifaz"},
  {"אליפלט","Elifelet"},
  {"אליקים","Eliakim"},
  {"אלישיב","Elyashiv"},
  {"אלישמע","Elishama"},
  {"אלמגור","Almagor"},
  {"אלמוג","Almog"},
  {"אלעד","El'ad"},
  {"אלעזר","Elazar"},
  {"אלפי מנשה","Alfei Menashe"},
  {"אלקוש","Elkosh"},
  {"אלקנה","Elkana"},
  {"אלרואי","Alrui"},
  {"אמונים","Emunim"},
  {"אמירים","Amirim"},
  {"אמנון","Amnon"},
  {"אמציה","Amatzia"},
  {"אניעם","Ani'am"},
  {"אעירה שחר","Aira Shahar"},
  {"אפיק","Afik"},
  {"אפיקים","Afikim"},
  {"אפק","Afek"},
  {"אפקה","Afeka"},
  {"אפרת","Efrat"},
  {"ארבל","Arbel"},
  {"ארגמן","Argaman"},
  {"ארז","Erez"},
  {"ארסוף","Arsuf"},
  {"ארסוף קדם","Arsuf Kedem"},
  {"אש קודש","Esh Kodesh"},
  {"אשבול","Eshbol"},
  {"אשבל","Eshbal"},
  {"אשדוד","Ashdod"},
  {"אשדוד","Ashdod"},
  {"אשדות יעקב איחוד","Ashdot Ya'akov Ihud"},
  {"אשדות יעקב מאוחד","Ashdot Ya'akov Meuhad"},
  {"אשחר","Eshhar"},
  {"אשכולות","Eshkolot"},
  {"אשל הנשיא","Eshel HaNasi"},
  {"אשלים","Ashalim"},
  {"אשקלון","Ashkelon"},
  {"אשרת","Oshrat"},
  {"אשתאול","Eshtaol"},
  {"באקה אל-גרביה","Baqa al-Gharbiyye"},
  {"באר גנים","Beer Ganim"},
  {"באר טוביה","Be'er Tuvia"},
  {"באר יעקב","Beer Yaakov"},
  {"באר מילכה","Be'er Milka"},
  {"באר-שבע","Beer Sheva"},
  {"בארות יצחק","Be'erot Yitzhak"},
  {"בארותיים","Beerotayim"},
  {"בארי","Be'eri"},
  {"בבלי","Bavli"},
  {"בוסתן הגליל","Bustan HaGalil"},
  {"בורגתה","Borgatha"},
  {"בורוכוב","Borochov"},
  {"בחן","Bahan"},
  {"בטחה","Bitha"},
  {"ביצרון","Bitzaron"},
  {"ביצרון ורמת ישראל","Bitzeron and Ramat Yisrael"},
  {"ביר א-סיכה","Bir a-Sikha"},
  {"ביר אל מכסור","Bir al-Maksur"},
  {"ביריה","Birya"},
  {"בית אורן","Beit Oren"},
  {"בית אל","Beit El"},
  {"בית אליעזר","Beit Eli'ezer"},
  {"בית אלעזרי","Beit Elazari"},
  {"בית אלפא","Beit Alfa"},
  {"בית אריה","Beit Aryeh"},
  {"בית גוברין","Beit Guvrin"},
  {"בית גמליאל","Beit Gamliel"},
  {"בית דגן","Beit Dagan"},
  {"בית הגדי","Beit HaGadi"},
  {"בית הלוי","Beit Halevi"},
  {"בית הלל","Beit Hillel"},
  {"בית העמק","Beit HaEmek"},
  {"בית הערבה","Beit HaArava"},
  {"בית השיטה","Beit Hashita"},
  {"בית זייד","Beit Zaid"},
  {"בית זית","Beit Zayit"},
  {"בית זרע","Beit Zera"},
  {"בית חגי","Bet Hagai"},
  {"בית חורון","Beit Horon"},
  {"בית חלקיה","Beit Hilkia"},
  {"בית חנן","Beit Hanan"},
  {"בית חנניה","Beit Hanania"},
  {"בית חרות","Beit Herut"},
  {"בית חשמונאי","Beit Hashmonai"},
  {"בית יהושע","Beit Yehoshua"},
  {"בית יוסף","Beit Yosef"},
  {"בית ינאי","Beit Yanai"},
  {"בית יצחק - שער חפר","Beit Yitzhak - Sha'ar Hefer"},
  {"בית יתיר","Beit Yatir"},
  {"בית לחם הגלילית","Bethlehem of Galilee"},
  {"בית מאיר","Beit Meir"},
  {"בית נחמיה","Beit Nehemia"},
  {"בית ניר","Beit Nir"},
  {"בית נקופה","Beit Nekofa"},
  {"בית עובד","Beit Oved"},
  {"בית עוזיאל","Beit Uziel"},
  {"בית עזרא","Beit Ezra"},
  {"בית עריף","Beit Arif"},
  {"בית קמה","Beit Kama"},
  {"בית קשת","Beit Keshet"},
  {"בית רבן - גבעת וושינגטון","Beit Raban - Givat Washington"},
  {"בית רימון","Beit Rimon"},
  {"בית שאן","Beit She'an"},
  {"בית שמש","Bet Shemesh"},
  {"בית שערים","Beit She'arim"},
  {"בית שקמה","Beit Shikma"},
  {"ביתן אהרן","Bitan Aharon"},
  {"ביתר עילית","Betar Illit"},
  {"בלפוריה","Balfouria"},
  {"בן זכאי","Ben Zakai"},
  {"בן עמי","Ben Ami"},
  {"בן שמן","Ben Shemen"},
  {"בני ברק","Bnei Brak"},
  {"בני דקלים","Bnei Dekalim"},
  {"בני דרום","Bnei Darom"},
  {"בני דרור","Bnei Dror"},
  {"בני יהודה","Bnei Yehuda"},
  {"בני נצרים","Bnei Netzarim"},
  {"בני עטרות","Bnei Atarot"},
  {"בני עי\"ש","Bnei Ayish"},
  {"בני ציון","Bnei Zion"},
  {"בני ראם","Bnei Re'em"},
  {"בניה","Bnaya"},
  {"בנימינה","Binyamina"},
  {"בצרה","Batzra"},
  {"בצת","Betzet"},
  {"בקוע","Beko'a"},
  {"בקעות","Beka'ot"},
  {"בקר","Beker"},
  {"בר אילן","Bar Ilan"},
  {"בר גיורא","Bar Giora"},
  {"בר יוחאי","Bar Yohai"},
  {"ברוכין","Bruchin"},
  {"ברור חיל","Boror Hail"},
  {"ברורים","Brurim"},
  {"ברוש","Brosh"},
  {"ברכיה","Berekhya"},
  {"ברעם","Bar'am"},
  {"ברק","Barak"},
  {"ברקאי","Barkai"},
  {"ברקן","Barkan"},
  {"ברקת","Bareket"},
  {"בת גנים","Bat Ganim"},
  {"בת הדר","Bat Hadar"},
  {"בת חן","Bat Hen"},
  {"בת חפר","Bat Hefer"},
  {"בת ים","Bat Yam"},
  {"בת ים","Bat Yam"},
  {"בת ים","Bat Yam"},
  {"בת עין","Bat Ayin"},
  {"בת שלמה","Bat Shlomo"},
  {"ג'לג'וליה","Jaljulia"},
  {"ג'נאביב","Janabib"},
  {"ג'סר א-זרקא","Jisr az-Zarqa"},
  {"ג׳ת","Jath"},
  {"גאולי תימן","Geulei Teiman"},
  {"גאולים","Geulim"},
  {"גאליה","Ge'alya"},
  {"גבולות","Gvulot"},
  {"גבים","Gevim"},
  {"גבע","Geva"},
  {"גבע בנימין (אדם)","Geva Binyamin (Adam)"},
  {"גבע כרמל","Geva Carmel"},
  {"גבעולים","Givolim"},
  {"גבעון החדשה","Giv'on HaHadasha"},
  {"גבעות","Giva'ot"},
  {"גבעות בר","Giv'ot Bar"},
  {"גבעת אבני","Giv'at Avni"},
  {"גבעת אולגה","Giv'at Olga"},
  {"גבעת אלה","Giv'at Ela"},
  {"גבעת ברנר","Giv'at Brenner"},
  {"גבעת המורה","Giv'at HaMore"},
  {"גבעת הרצל","Giv'at Herzl"},
  {"גבעת הרקפות","Giv'at Harekafot"},
  {"גבעת השלושה","Giv'at HaShlosha"},
  {"גבעת וולפסון","Giv'at Wolfson"},
  {"גבעת זאב","Giv'at Ze'ev"},
  {"גבעת ח\"ן","Giv'at Hen"},
  {"גבעת חביבה","Givat Haviva"}, //////////////////////////////////////////////////////////////////////////////////////
  {"גבעת חיים (איחוד)","Giv'at Haim (Ichud)"},
  {"גבעת חיים (מאוחד)","Giv'at Haim (Meuchad)"},
  {"גבעת טל","Giv'at Tal"},
  {"גבעת יואב","Giv'at Yoav"},
  {"גבעת יערים","Giv'at Ye'arim"},
  {"גבעת ישעיהו","Giv'at Yeshayahu"},
  {"גבעת כח","Giv'at Ko'ah"},
  {"גבעת משה","Giv'at Moshe"},
  {"גבעת ניל\"י","Giv'at Nili"},
  {"גבעת עדה","Giv'at Ada"},
  {"גבעת עוז","Giv'at Oz"},
  {"גבעת רם","Giv'at Ram"},
  {"גבעת שמואל","Giv'at Shmuel"},
  {"גבעת שפירא","Giv'at Shapira"},
  {"גבעתי","Giv'ati"},
  {"גבעתיים","Giv'atayim"},
  {"גברעם","Gvar'am"},
  {"גבת","Gvat"},
  {"גדות","Gadot"},
  {"גדיש","Gadish"},
  {"גדעונה","Gidona"},
  {"גדרה","Gedera"},
  {"גונן","Gonen"},
  {"גורן","Goren"},
  {"גזית","Gazit"},
  {"גזר","Gezer"},
  {"גיאה","Ge'a"},
  {"גיבתון","Gibton"},
  {"גיזו","Gizo"},
  {"גילון","Gilon"},
  {"גילעם","Gilam"},
  {"גילת","Gilat"},
  {"גינוסר","Ginosar"},
  {"גינתון","Ginaton"},
  {"גיתה","Gita"},
  {"גיתית","Gitit"},
  {"גלאון","Gal On"},
  {"גלגל","Gilgal"},
  {"גליל ים","Glil Yam"},
  {"גלילות","Glilot"},
  {"גלעד","Gal'ed"},
  {"גמזו","Gimzo"},
  {"גן הדרום","Gan HaDarom"},
  {"גן השומרון","Gan HaShomron"},
  {"גן השרון","Gan HaSharon"},
  {"גן חיים","Gan Haim"},
  {"גן יאשיה","Gan Yoshiya"},
  {"גן יבנה","Gan Yavne"},
  {"גן נר","Gan Ner"},
  {"גן שורק","Gan Sorek"},
  {"גן שלמה (קבוצת שילר)","Gan Shlomo (Schiller Group)"},
  {"גן שמואל","Gan Shmuel"},
  {"גנות","Ganot"},
  {"גנות הדר","Ganot Hadar"},
  {"גני הדר","Ganei Hadar"},
  {"גני טל","Ganei Tal"},
  {"גני יהודה","Ganei Yehuda"},
  {"גני יוחנן","Ganei Yohanan"},
  {"גני מודיעין","Ganei Modi'in"},
  {"גני עם","Ganei Am"},
  {"גני צהלה, רמות צהלה","Ganei Tzahala,  Ramot Tzahala"},
  {"גני שרונה","Ganei Sarona"},
  {"גניגר","Ginegar"},
  {"געש","Ga'ash"},
  {"געתון","Gaaton"},
  {"גפן","Gefen"},
  {"גרופית","Grofit"},
  {"גרנות הגליל","Gornot HaGalil"},
  {"גשור","Geshur"},
  {"גשר","Gesher"},
  {"גשר הזיו","Gesher HaZiv"},
  {"גת","Gat"},
  {"גת רימון","Gat Rimon"},
  {"דבורה","Dvora"},
  {"דביר","Dvir"},
  {"דברת","Dovrat"},
  {"דגניה א'","Degania Alef"},
  {"דגניה ב'","Degania Bet"},
  {"דוב״ב","Dovev"},
  {"דולב","Dolev"},
  {"דור","Dor"},
  {"דורות","Dorot"},
  {"דימונה","Dimona"},
  {"דישון","Dishon"},
  {"דליה","Dalia"},
  {"דלתון","Dalton"},
  {"דן","Dan"},
  {"דפנה","Dafna"},
  {"דקל","Dekel"},
  {"האון","HaOn"},
  {"הבונים","HaBonim"},
  {"הבורסה","HaBursa"},
  {"הגושרים","HaGoshrim"},
  {"הדר גנים","Hadar Ganim"},
  {"הדר עם","Hadar Am"},
  {"הדר-יוסף","Hadar-Yosef"},
  {"הוד השרון","Hod Hasharon"},
  {"הודיה","Hodaya"},
  {"הושעיה","Hoshaya"},
  {"הזורע","HaZore'a"},
  {"הזורעים","HaZor'im"},
  {"החווה החקלאית","Hahafarm"},
  {"החווה של מיכה","Micha's Farm"},
  {"החותרים","HaHotrim"},
  {"היוגב","HaYogev"},
  {"הכפר הירוק","HaKfar HaYarok"},
  {"המעפיל","HaMa'apil"},
  {"המשתלה","HaMishtalah"},
  {"הסוללים","HaSolelim"},
  {"העוגן","HaOgen"},
  {"העיר העתיקה","The Old City"},
  {"הצפון החדש - החלק הדרומי","The New North - Southern Part"},
  {"הצפון החדש - החלק הצפוני","The New North - Northern Part"},
  {"הצפון החדש - סביבת ככר המדינה","The New North - State Square Area"},
  {"הצפון הישן - החלק הדרומי","The Old North - Southern Part"},
  {"הצפון הישן - החלק הצפוני","The Old North - Northern Part"},
  {"הר אדר","Har Adar"},
  {"הר ברכה","Har Brakha"},
  {"הר חלוץ","Har Halutz"},
  {"הר כתרון","Har Kitron"},
  {"הר נחום","Har Nakhum"},
  {"הר עמשא","Har Amasa"},
  {"הר ציון","Har Zion"},
  {"הר ציון","Har Zion"},
  {"הראל","Harel"},
  {"הרדוף","Harduf"},
  {"הרצליה","Herzliya"},
  {"הרצליה","Herzliya"},
  {"הררית","Hararit"},
  {"השכונה הוותיקה","The Old Neighborhood"},
  {"התמר","HaTamar"},
  {"התקוה","HaTikva"},
  {"ורד יריחו","Vered Yeriho"},
  {"ורדון","Vardon"},
  {"ותיקים","Vatikim"},
  {"זבדיאל","Zavdiel"},
  {"זוהר","Zohar"},
  {"זימרת","Zimrat"},
  {"זיקים","Zikim"},
  {"זיתן","Zeitan"},
  {"זכרון יעקב","Zikhron Ya'akov"},
  {"זכריה","Zekharia"},
  {"זנוח","Zano'ah"},
  {"זרועה","Zarua"},
  {"זרחיה","Zrahia"},
  {"זרעית","Zar'it"},
  {"חאן ארץ המרדפים","Khan Eretz Mardoch"},
  {"חבצלת השרון","Havatzelet HaSharon"},
  {"חבר","Hever"},
  {"חגור","Hagor"},
  {"חגלה","Hogla"},
  {"חד נס","Had Ness"},
  {"חדיד","Hadid"},
  {"חדרה","Hadera"},
  {"חוג'ייראת","Hujeirat"},
  {"חוואלד","Khawaled"},
  {"חווה","Hava"},
  {"חוות אורליה","Aurelia Farm"},
  {"חוות אלה (צדק)","Ela Farm (Tzedek)"},
  {"חוות גל יוסף","Gal Yosef Farm"},
  {"חוות גלעד","Gilad Farm"},
  {"חוות העיטם","Aitam Farm"},
  {"חוות מדבר חבר","Hever Desert Farm"},
  {"חוות מעון","Maon Farm"},
  {"חוות מעיין הנעורים","Maayan Hanaurim Farm"},
  {"חוות סוסים","Horse Farm"},
  {"חוות עזים","Goat Farm"},
  {"חוות צוק","Zuk Farm"},
  {"חוות צרדה","Tserada Farm"},
  {"חוות שקד","Shaked Farm"},
  {"חולדה","Hulda"},
  {"חולון","Holon"},
  {"חולית","Holit"},
  {"חולתה","Hulata"},
  {"חוסן","Hosen"},
  {"חופית","Hofit"},
  {"חוקוק","Hukok"},
  {"חורשים","Horshim"},
  {"חות עדן","Khavat Eden"},
  {"חזון","Hazon"},
  {"חיבת ציון","Hibat Zion"},
  {"חילף","Hilf"},
  {"חיננית","Hinanit"},
  {"חיספין","Hispin"},
  {"חיפה","Haifa"},
  {"חלץ","Heletz"},
  {"חמ\"ד (מושב)","Hemed (Moshav)"},
  {"חמדיה","Hamadia"},
  {"חמדת","Hemdat"},
  {"חמדת ימים","Hemdat Yamim"},
  {"חמרה","Hamra"},
  {"חניאל","Haniel"},
  {"חניתה","Hanita"},
  {"חנתון","Hanaton"},
  {"חפץ חיים","Hafetz Haim"},
  {"חפציבה","Heftziba"},
  {"חצב","Hatsav"},
  {"חצבה","Hazeva"},
  {"חצור אשדוד","Hatsor Ashdod"},
  {"חצור הגלילית","Hatzor HaGlilit"},
  {"חצרים","Hatzerim"},
  {"חרב לאת","Herev Le'et"},
  {"חרוזים","Haruzim"},
  {"חרוצים","Harutzim"},
  {"חרות","Herut"},
  {"חריש","Harish"},
  {"חרמש","Hermesh"},
  {"חרשים","Harashim"},
  {"חשמונאים","Hashmona'im"},
  {"חשמונאים","Hashmona'im"},
  {"טבחה","Tabgha"},
  {"טבריה","Tiberias"},
  {"טירה","Tira"},
  {"טירת יהודה","Tirat Yehuda"},
  {"טירת כרמל","Tirat Carmel"},
  {"טירת שלום","Tirat Shalom"},
  {"טל אור","Tal Or"},
  {"טל מנשה","Tal Menashe"},
  {"טל שחר","Tal Shahar"},
  {"טל-אל","Tal-El"},
  {"טללים","Tlalim"},
  {"טלמון","Talmon"},
  {"טמרה","Tamra"},
  {"טפחות","Tefahot"},
  {"יבול","Yevul"},
  {"יבנאל","Yavne'el"},
  {"יבנה","Yavne"},
  {"יגור","Yagur"},
  {"יגל","Yagel"},
  {"יד אליהו","Yad Eliyahu"},
  {"יד בנימין","Yad Binyamin"},
  {"יד השמונה","Yad HaShmona"},
  {"יד חנה","Yad Hana"},
  {"יד נתן","Yad Natan"},
  {"יד רמב\"ם","Yad Rambam"},
  {"יהוד מונוסון","Yehud-Monosson"},
  {"יהל","Yahalal"},
  {"יהלום","Yahloom"},
  {"יובלים","Yuvalim"},
  {"יודפת","Yodfat"},
  {"יונתן","Yonatan"},
  {"יוקנעם המושבה","Yokne'am HaMoshava"},
  {"יוקנעם עילית","Yokne'am Illit"},
  {"יושיביה","Yoshivia"},
  {"יזרעאל","Yizre'el"},
  {"יחד","Yahad"},
  {"יחיעם","Yehiam"},
  {"יטבתה","Yotvata"},
  {"ייט\"ב","Yitav"},
  {"יישוב בדואי","Bedouin Settlement"},
  {"יכיני","Yakhini"},
  {"ימה","Yama"},
  {"ימין אורד","Yemin Orde"},
  {"ינוב","Yanuv"},
  {"ינון","Yinon"},
  {"יסוד המעלה","Yesud HaMa'ala"},
  {"יסודות","Yesodot"},
  {"יעד","Ya'ad"},
  {"יעל","Yael"},
  {"יעף","Ye'af"},
  {"יערה","Ya'ara"},
  {"יפו ג' ונוה גולן","Jaffa G and Neve Golan"},
  {"יפו העתיקה,נמל יפו","Old Jaffa, Jaffa Port"},
  {"יפיע","Yafia"},
  {"יפית","Yafit"},
  {"יפעת","Yifat"},
  {"יפתח","Yiftah"},
  {"יצהר","Yitzhar"},
  {"יצהר","Yitzhar"},
  {"יציץ","Yatzitz"},
  {"יקום","Yakum"},
  {"יקיר","Yakir"},
  {"יראון","Yir'on"},
  {"ירד","Yard"},
  {"ירדנה","Yardena"},
  {"ירוחם","Yeruham"},
  {"ירושלים","Jerusalem"},
  {"ירושלים | القدس","Jerusalem"},
  {"ירחיב","Yarhiv"},
  {"ירכא","Yarka"},
  {"ירקונה","Yarkona"},
  {"ישוב בדואי","Bedouin Settlement"},
  {"ישוב הדעת","Yeshuv Hada' at"},
  {"ישע","Yasha"},
  {"ישעי","Yish'i"},
  {"ישרש","Yashresh"},
  {"יתד","Yated"},
  {"כאבול","Kabul"},
  {"כברי","Kabri"},
  {"כדיתה","Kadita"},
  {"כוכב הצפון","Kochav HaTzafon"},
  {"כוכב השחר","Kokhav HaShahar"},
  {"כוכב יאיר צור יגאל","Kokhav Yair Tzur Yigal"},
  {"כוכב יעקב","Kokhav Ya'akov"},
  {"כוכב מיכאל","Kokhav Michael"},
  {"כורזים","Chorazim"},
  {"כחל","Kahal"},
  {"כיסופים","Kissufim"},
  {"כישור","Kishor"},
  {"כליל","Klil"},
  {"כלנית","Kalanit"},
  {"כמאנה מזרחית","Kamana Mizrahit"},
  {"כמהין","Kmehin"},
  {"כמון","Kamon"},
  {"כנות","Kannot"},
  {"כנף","Kanaf"},
  {"כנרת מושבה","Kinneret Moshav"},
  {"כסלון","Ksalon"},
  {"כפיר","Kfir"},
  {"כפר אביב","Kfar Aviv"},
  {"כפר אדומים","Kfar Adumim"},
  {"כפר אהרון","Kfar Aharon"},
  {"כפר אוריה","Kfar Uria"},
  {"כפר אז\"ר","Kfar Azar"},
  {"כפר אחים","Kfar Ahim"},
  {"כפר אלדד","Kfar Eldad"},
  {"כפר ביאליק","Kfar Bialik"},
  {"כפר ביל\"ו","Kfar Bilu"},
  {"כפר ביל\"ו ב׳","Kfar Bilu B"},
  {"כפר בלום","Kfar Blum"},
  {"כפר בן-נון","Kfar Bin Nun"},
  {"כפר ברא","Kafr Bara"},
  {"כפר ברוך","Kfar Baruch"},
  {"כפר גדעון","Kfar Gidon"},
  {"כפר גלים","Kfar Galim"},
  {"כפר גליקסון","Kfar Glikson"},
  {"כפר גלעדי","Kfar Giladi"},
  {"כפר גנים א'","Kfar Ganim A"},
  {"כפר גנים ב'","Kfar Ganim B"},
  {"כפר דניאל","Kfar Daniel"},
  {"כפר האורנים","Kfar Ha-Oranim"},
  {"כפר החורש","Kfar HaHoresh"},
  {"כפר המכבי","Kfar HaMaccabi"},
  {"כפר הנגיד","Kfar HaNagid"},
  {"כפר הנוער בן שמן","Ben Shemen Youth Village"},
  {"כפר הנוער הדתי","Kfar HaNoar HaDati"},
  {"כפר הנוער מאיר שפיה","Meir Shefia Youth Village"},
  {"כפר הנשיא","Kfar HaNassi"},
  {"כפר הס","Kfar Hess"},
  {"כפר הרא״ה","Kfar Haroeh"},
  {"כפר הרי״ף","Kfar HaRif"},
  {"כפר ויתקין","Kfar Vitkin"},
  {"כפר ורבורג","Kfar Warburg"},
  {"כפר ורדים","Kfar Vradim"},
  {"כפר זיתים","Kfar Zeitim"},
  {"כפר חב\"ד","Kfar Habad"},
  {"כפר חושן","Kfar Hoshen"},
  {"כפר חיטים","Kfar Hittim"},
  {"כפר חיים","Kfar Haim"},
  {"כפר חנניה","Kfar Hananya"},
  {"כפר חסידים","Kfar Hasidim"},
  {"כפר חרוב","Kfar Haruv"},
  {"כפר טרומן","Kfar Truman"},
  {"כפר ידידיה","Kfar Yedidia"},
  {"כפר יהושע","Kfar Yehoshua"},
  {"כפר יובל","Kfar Yuval"},
  {"כפר יונה","Kfar Yona"},
  {"כפר יחזקאל","Kfar Yehezkel"},
  {"כפר יעבץ","Kfar Yavetz"},
  {"כפר כנא","Kafr Kanna"},
  {"כפר מונש","Kfar Monash"},
  {"כפר מימון","Kfar Maimon"},
  {"כפר מל\"ל","Kfar Malal"},
  {"כפר מנחם","Kfar Menahem"},
  {"כפר מסריק","Kfar Masarik"},
  {"כפר מעש","Kfar Ma'as"},
  {"כפר מרדכי","Kfar Mordechai"},
  {"כפר מרדכי","Kfar Mordechai"},
  {"כפר נופש רקפת","Kfar Nofush Rakefet"},
  {"כפר נטר","Kfar Netter"},
  {"כפר סאלד","Kfar Szold"},
  {"כפר סבא","Kfar Saba"},
  {"כפר סבא הירוקה","Kfar Saba Ya'ruka"},
  {"כפר סירקין","Kfar Sirkin"},
  {"כפר עבודה","Kfar Avoda"},
  {"כפר עזה","Kfar Aza"},
  {"כפר עציון","Kfar Ezion"},
  {"כפר פינס","Kfar Pines"},
  {"כפר קאסם","Kfar Qasim"},
  {"כפר קיש","Kfar Kisch"},
  {"כפר קרע","Kfar Qara"},
  {"כפר רופין","Kfar Ruppin"},
  {"כפר רות","Kfar Rut"},
  {"כפר רפאל","Kfar Rafael"},
  {"כפר שמאי","Kfar Shamai"},
  {"כפר שמואל","Kfar Shmuel"},
  {"כפר שמריהו","Kfar Shmaryahu"},
  {"כפר תבור","Kfar Tavor"},
  {"כפר תפוח","Kfar Tapuach"},
  {"כפר תקווה","Kfar Tikva"},
  {"כרי דשא","Karei Deshe"},
  {"כרכום","Karkom"},
  {"כרם בן זמרה","Kerem Ben Zimra"},
  {"כרם בן שמן","Kram Ben Shemen"},
  {"כרם התימנים","Kerem HaTeimanim"},
  {"כרם מהר״ל","Kerem Maharal"},
  {"כרם שלום","Kerem Shalom"},
  {"כרמי יוסף","Karmei Yosef"},
  {"כרמי צור","Karmei Zur"},
  {"כרמים","Kramim"},
  {"כרמית","Carmit"},
  {"כרמל","Carmel"},
  {"לב תל-אביב","Lev Tel Aviv"},
  {"לבון","Lavon"},
  {"לביא","Lavi"},
  {"לבנה, ידידיה","Levna, Yedidia"},
  {"להב","Lahav"},
  {"להבה","Lahava"},
  {"להבות הבשן","Lehavot HaBashan"},
  {"להבות חביבה","Lehavot Haviva"},
  {"להבים","Lehavim "},
  {"לוד","Lod"},
  {"לוזית","Luzit"},
  {"לוחמי הגטאות","Lohamei HaGeta'ot"},
  {"לוטם","Lotem"},
  {"לוטן","Lotan"},
  {"ליבנים","Livnim"},
  {"לימן","Liman"},
  {"לכיש","Lachish"},
  {"לפיד","Lapid"},
  {"לפידות","Lapidot"},
  {"מאור","Maor"},
  {"מבוא ביתר","Mevo Beitar"},
  {"מבוא דותן","Mevo Dotan"},
  {"מבוא חורון","Mevo Horon"},
  {"מבוא חמה","Mevo Hama"},
  {"מבואות יריחו","Mevo'ot Yericho"},
  {"מבועים","Mabu'im"},
  {"מבטחים","Mivtahim"},
  {"מבקיעים","Mavki'im"},
  {"מבשרת ציון","Mevaseret Zion"},
  {"מגד שמים","Meged Shaamim"},
  {"מגדים","Megadim"},
  {"מגדל","Migdal"},
  {"מגדל העמק","Migdal HaEmek"},
  {"מגדל עוז","Migdal Oz"},
  {"מגדלים","Migdalim"},
  {"מגידו","Megiddo"},
  {"מגל","Magal"},
  {"מגן","Magen"},
  {"מגן שאול","Magen Shaul"},
  {"מגשימים","Magshimim"},
  {"מדרך עוז","Midrakh Oz"},
  {"מדרשת בן גוריון","Midreshet Ben-Gurion"},
  {"מודיעין-מכבים-רעות","Modi'in-Maccabim-Reut"},
  {"מולדת","Moledet"},
  {"מונטיפיורי","Montefiore"},
  {"מועאוויה","Mu'awiya"},
  {"מוצא","Motza"},
  {"מוצא עילית","Motza Illit"},
  {"מורן","Moran"},
  {"מורשת","Moreshet"},
  {"מושב מרחביה","Moshav Merhavia"},
  {"מזור","Mazor"},
  {"מזכרת בתיה","Mazkeret Batya"},
  {"מזרע","Mizra"},
  {"מחולה","Mehola"},
  {"מחנה יהודה","Mahane Yehuda"},
  {"מחניים","Mahanayim"},
  {"מחסיה","Mahseya"},
  {"מטולה","Metula"},
  {"מטולה","Metula"},
  {"מטע","Mata"},
  {"מי עמי","Mei Ami"},
  {"מיטב","Meitav"},
  {"מיצד","Metzad"},
  {"מיצר","Metzar"},
  {"מירב","Meirav"},
  {"מירון","Meron"},
  {"מישור אדומים","Mishor Adumim"},
  {"מישר","Meishar"},
  {"מיתר","Meitar"},
  {"מכללת יפו תל אביב ודקר","Jaffa College Tel Aviv and Dakar"},
  {"מכמורת","Mikhmoret"},
  {"מכמנים","Mikhmanim"},
  {"מלאה","Mle'a"},
  {"מלילות","Mlilot"},
  {"מלכיה","Malkia"},
  {"מלכישוע","Malkishua"},
  {"מנוחה","Menuha"},
  {"מנוף","Manof"},
  {"מנות","Manot"},
  {"מנחמיה","Menahemia"},
  {"מנרה","Manara"},
  {"מסד","Massad"},
  {"מסדה","Massada"},
  {"מסילות","Mesilot"},
  {"מסילת ציון","Mesilat Zion"},
  {"מסלול","Maslul"},
  {"מעברות","Ma'abarot"},
  {"מעגלים","Ma'agalim"},
  {"מעגן","Ma'agan"},
  {"מעגן מיכאל","Ma'agan Michael"},
  {"מעוז אביב","Ma'oz Aviv"},
  {"מעוז אסתר","Ma'oz Esther"},
  {"מעוז חיים","Ma'oz Haim"},
  {"מעוז צבי","Ma'oz Tzvi"},
  {"מעוז ציון","Ma'oz Tzvi"},
  {"מעון","Ma'on"},
  {"מעונה","Me'ona"},
  {"מעיין ברוך","Ma'ayan Baruch"},
  {"מעיין צבי","Ma'ayan Tzvi"},
  {"מעלה אדומים","Ma'ale Adumim"},
  {"מעלה אפרים","Ma'ale Efrayim"},
  {"מעלה גלבוע","Ma'ale Gilboa"},
  {"מעלה גמלא","Ma'ale Gamla"},
  {"מעלה החמישה","Ma'ale HaHamisha"},
  {"מעלה לבונה","Ma'ale Levona"},
  {"מעלה מכמש","Ma'ale Michmash"},
  {"מעלה עמוס","Ma'ale Amos"},
  {"מעלה צביה","Ma'ale Tzvia"},
  {"מעלה רחבעם","Ma'ale Rehav'am"},
  {"מעלות תרשיחא","Ma'alot-Tarshiha"},
  {"מענית","Ma'anit"},
  {"מפלסים","Mefalsim"},
  {"מצובה","Matzuva"},
  {"מצוקי דרגות","Metsoke Dragot"},
  {"מצליח","Matsli'ah"},
  {"מצפה","Mitzpa"},
  {"מצפה אביב","Mitzpe Aviv"},
  {"מצפה אילן","Mitzpe Ilan"},
  {"מצפה דני","Mitzpe Dani"},
  {"מצפה הילה","Mitzpe Hila"},
  {"מצפה חגית","Mitzpe Hagit"},
  {"מצפה יצהר","Mitspe Yits'har"},
  {"מצפה יריחו","Mitzpe Yeriho"},
  {"מצפה כרמים","Mitzpe Kramim"},
  {"מצפה נטופה","Mitzpe Netofa"},
  {"מצפה רמון","Mitzpe Ramon"},
  {"מצר","Metzer"},
  {"מרג'ה","Marja"},
  {"מרגליות","Margaliot"},
  {"מרום גולן","Merom Golan"},
  {"מרחב עם","Merhav Am"},
  {"מרכז הירידים","Merkaz HaYeridim"},
  {"מרכז שפירא","Merkaz Shapira"},
  {"משאבי שדה","Mashabei Sadeh"},
  {"משגב דב","Misgav Dov"},
  {"משגב עם","Misgav Am"},
  {"משהד","Mashhad"},
  {"משואה","Masu'a"},
  {"משואות יצחק","Masu'ot Itzhak"},
  {"משכיות","Maskiot"},
  {"משכנות הראל","Mishkenot Harel"},
  {"משמר איילון","Mishmar Ayalon"},
  {"משמר דוד","Mishmar David"},
  {"משמר הירדן","Mishmar HaYarden"},
  {"משמר הנגב","Mishmar HaNegev"},
  {"משמר העמק","Mishmar HaEmek"},
  {"משמר השבעה","Mishmar HaShiva"},
  {"משמר השרון","Mishmar HaSharon"},
  {"משמרות","Mishmarot"},
  {"משמרת","Mishmeret"},
  {"משען","Mash'en"},
  {"מתן","Matan"},
  {"מתת","Mattat"},
  {"מתתיהו","Matityahu"},
  {"נאות אברהם","Ne'ot Avraham"},
  {"נאות אפקה א","Ne'ot Afka A"},
  {"נאות גולן","Ne'ot Golan"},
  {"נאות לון","Ne'ot Lon"},
  {"נאות מרדכי","Ne'ot Mordechai"},
  {"נאות סמדר","Ne'ot Smadar"},
  {"נבטים","Nevatim"},
  {"נבטים","Nevatim"},
  {"נגבה","Negba"},
  {"נגוהות","Negohot"},
  {"נגוהות","Negohot"},
  {"נהורה","Nehora"},
  {"נהלל","Nahalal"},
  {"נהריה","Nahriya"},
  {"נוב","Nov"},
  {"נוגה","Noga"},
  {"נוה אביבים וסביבתה","Neve Avivim and its surroundings"},
  {"נוה אילן","Neve Ilan"},
  {"נוה איתמר","Neve Itamar"},
  {"נוה אליעזר וכפר שלם מזרח","Neve Eli'ezer and Kfar Shalem East"},
  {"נוה ברבור, כפר שלם מערב","Neve Barbur, Kfar Shalem West"},
  {"נוה דן","Neve Dan"},
  {"נוה חן","Neve Hen"},
  {"נוה ימין","Neve Yamin"},
  {"נוה מונוסון","Neve Monosson"},
  {"נוה צדק","Neve Tzedek"},
  {"נוה שלום","Neve Shalom"},
  {"נוה שמיר","Neve Shamir"},
  {"נווה","Neve"},
  {"נווה אור","Neve Or"},
  {"נווה אטי\"ב","Neve Ativ"},
  {"נווה איתן","Neve Eitan"},
  {"נווה דניאל","Neve Daniel"},
  {"נווה זאב","Neve Ze'ev"},
  {"נווה זוהר","Neve Zohar"},
  {"נווה זיו","Neve Ziv"},
  {"נווה חריף","Neve Harif"},
  {"נווה יהושע","Neve Yehoshua"},
  {"נווה ים","Neve Yam"},
  {"נווה ירק","Neve Yarak"},
  {"נווה מבטח","Neve Mivtah"},
  {"נווה מיכאל","Neve Michael"},
  {"נווה עופר","Neve Ofer"},
  {"נווה עמיאל","Neve Amiel"},
  {"נווה צוף","Neve Tzuf"},
  {"נווה שאנן","Neve Sha'anan"},
  {"נווה שרת","Neve Sharet"},
  {"נועם","Noam"},
  {"נוף איילון","Nof Ayalon"},
  {"נוף הגליל","Nof HaGalil"},
  {"נוף ים","Nof Yam"},
  {"נופי אבטליון","Nofei Avtalyon"},
  {"נופי ים","Nofei Yam"},
  {"נופי נחמיה","Nofei Nekhemia"},
  {"נופי פרת","Nofei Prat"},
  {"נופים","Nofim"},
  {"נופית","Nofit"},
  {"נופך","Nofekh"},
  {"נוקדים","Nokdim"},
  {"נורדיה","Nordia"},
  {"נורית","Nurit"},
  {"נח\"ל שיטים","Nahal Shitim"},
  {"נחושה","Nehusha"},
  {"נחל עוז","Nahal Oz"},
  {"נחלה","Nahalal"},
  {"נחלה","Nahalal"},
  {"נחליאל","Nahliel"},
  {"נחלים","Nehalim"},
  {"נחלת גנים","Nahalat Ganim"},
  {"נחלת יצחק","Nahalat Yitzhak"},
  {"נחם","Naham"},
  {"נחשולים","Nahsholim"},
  {"נחשון","Nahshon"},
  {"נחשונים","Nahshonim"},
  {"נטועה","Netu'a"},
  {"נטור","Natur"},
  {"נטעים","Neta'im"},
  {"נטף","Nataf"},
  {"ניבה","Niva"},
  {"ניל\"י","Nili\"i"},
  {"ניצן","Nitzan"},
  {"ניצן ב׳","Nitzan Bet"},
  {"ניצנה","Nitzana"},
  {"ניצני סיני","Nitzanei Sinai"},
  {"ניצני עוז","Nitzanei Oz"},
  {"ניצנים","Nitzanim"},
  {"ניר אביב","Nir Aviv"},
  {"ניר אליהו","Nir Eliyahu"},
  {"ניר בנים","Nir Banim"},
  {"ניר גלים","Nir Galim"},
  {"ניר דוד","Nir David"},
  {"ניר ח״ן","Nir Hen"},
  {"ניר יפה","Nir Yafeh"},
  {"ניר יצחק","Nir Yitzhak"},
  {"ניר ישראל","Nir Yisrael"},
  {"ניר משה","Nir Moshe"},
  {"ניר עוז","Nir Oz"},
  {"ניר עם","Nir Am"},
  {"ניר עציון","Nir Etzion"},
  {"ניר עקיבא","Nir Akiva"},
  {"ניר צבי","Nir Tzvi"},
  {"נירים","Nirim"},
  {"נירית","Nirit"},
  {"נמל תל-אביב","Tel Aviv Port"},
  {"נמרוד","Nimrod"},
  {"נס הרים","Nes Harim"},
  {"נס עמים","Nes Ammim"},
  {"נס ציונה","Nes Ziona"},
  {"נס ציונה","Nes Ziona"},
  {"נעורים","Ne'urim"},
  {"נעלה","Na'ale"},
  {"נעמה","Na'ama"},
  {"נען","Na'an"},
  {"נצאצרה","Nasasra"},
  {"נצר חזני","Netzer Hazani"},
  {"נצר סרני","Netzer Sereni"},
  {"נצרת","Nazareth"},
  {"נריה","Neria"},
  {"נשר","Nesher"},
  {"נתיב הגדוד","Netiv HaGdud"},
  {"נתיב הל\"ה","Netiv HaLamed-Heh"},
  {"נתיב העשרה","Netiv HaAsara"},
  {"נתיב השיירה","Netiv HaShayara"},
  {"נתיבות","Netivot"},
  {"נתניה","Netanya"},
  {"סאסא","Sasa"},
  {"סביון","Savyon"},
  {"סגולה","Sgula"},
  {"סוסיה","Susya"},
  {"סופה","Sufa"},
  {"סיטי","City"},
  {"סיקורה","Sikora"},
  {"סלעית","Sal'it"},
  {"סמר","Samar"},
  {"סנסנה","Sansana"},
  {"סעד","Sa'ad"},
  {"סער","Sa'ar"},
  {"ספיר","Sapir"},
  {"סתריה","Sitria"},
  {"עארה","Aara"},
  {"עבדון","Abdon"},
  {"עברון","Evron"},
  {"עג'מי וגבעת עליה","Ajami and Givat Aliya"},
  {"עגור","Agur"},
  {"עדי","Adi"},
  {"עדי עד","Adei Ad"},
  {"עדנים","Adanim"},
  {"עוזה","Uza"},
  {"עולש","Olesh"},
  {"עומר","Omer"},
  {"עופר","Ofer"},
  {"עוצם","Otzem"},
  {"עזוז","Ezuz"},
  {"עזר","Ezer"},
  {"עזרא והארגזים","Ezra and the Arkesheim"},
  {"עזריאל","Azri'el"},
  {"עזריה","Azaria"},
  {"עזריקם","Azrikam"},
  {"עטרת","Ateret"},
  {"עיבל","Ibel"},
  {"עיבלין","I'billin"},
  {"עידן","Idan"},
  {"עיינות","Ayanot"},
  {"עין איילה","Ein Ayala"},
  {"עין גב","Ein Gev"},
  {"עין גדי","Ein Gedi"},
  {"עין דור","Ein Dor"},
  {"עין הבשור","Ein Besor"},
  {"עין הוד","Ein Hod"},
  {"עין החורש","Ein HaHoresh"},
  {"עין המפרץ","Ein HaMifratz"},
  {"עין הנציב","Ein HaNatziv"},
  {"עין העמק","Ein HaEmek"},
  {"עין השופט","Ein HaShofet"},
  {"עין השלושה","Ein HaShlosha"},
  {"עין ורד","Ein Vered"},
  {"עין זיוון","Ein Zivan"},
  {"עין חצבה","Ein Hatzeva"},
  {"עין חרוד","Ein Harod"},
  {"עין יהב","Ein Yahav"},
  {"עין יעקב","Ein Ya'akov"},
  {"עין כרמל","Ein Carmel"},
  {"עין מאהל","Ein Mahil"},
  {"עין נקובא","Ein Naqquba"},
  {"עין עירון","Ein Iron"},
  {"עין צורים","Ein Tzurim"},
  {"עין ראפה","Ein Rafa"},
  {"עין שמר","Ein Shemer"},
  {"עין שריד","Ein Sarid"},
  {"עין תמר","Ein Tamar"},
  {"עינב","Einav"},
  {"עינת","Einat"},
  {"עכברה","Akbara"},
  {"עכו","Akko"},
  {"עלומים","Alumim"},
  {"עלי","Eli"},
  {"עלי זהב","Alei Zahav"},
  {"עליות","Aliot"},
  {"עלמה","Alma"},
  {"עלמון","Almon"},
  {"עמוקה","Amuka"},
  {"עמינדב","Aminadav"},
  {"עמיעד","Ami'ad"},
  {"עמיעוז","Ami'oz"},
  {"עמיקם","Amikam"},
  {"עמיר","Amir"},
  {"עמנואל","Immanuel"},
  {"עמקה","Amka"},
  {"עפולה","Afula"},
  {"עפולה עילית","Afula Illit"},
  {"עפרה","Ofra"},
  {"עץ אפרים","Ets Efraim"},
  {"עצמון שגב","Atzmon Segev"},
  {"ערד","Arad"},
  {"ערוגות","Arugot"},
  {"ערוגות רבקה","Arugot Rivkah"},
  {"עשהאל","Asael"},
  {"עשרת","Aseret"},
  {"עתלית","Atlit"},
  {"עתניאל","Otniel"},
  {"פארן","Paran"},
  {"פארק דרום","Park Darom"},
  {"פארק החורשות","Park HaHorshot"},
  {"פדואל","Pedu'el"},
  {"פדויים","Peduim"},
  {"פדיה","Pedaya"},
  {"פוריה - נווה עובד","Poria - Neve Oved"},
  {"פוריה כפר עבודה","Poria - Kfar Avoda"},
  {"פוריה עילית","Poria Illit"},
  {"פורת","Porat"},
  {"פטיש","Patish"},
  {"פלורנטין","Florentin"},
  {"פלך","Pelekh"},
  {"פלמחים","Palmachim"},
  {"פני קדם","Pnei Kedem"},
  {"פסגות","Psagot"},
  {"פעמי תש\"ז","Pa'amei Tashaz"},
  {"פצאל","Petza'el"},
  {"פקיעין החדשה","Peki'in HaHadasha"},
  {"פרדס חנה-כרכור","Pardes Hanna-Karkur"},
  {"פרדסיה","Pardesiya"},
  {"פרוד","Parod"},
  {"פרזון","Prazon"},
  {"פרי גן","Pri Gan"},
  {"פתח תקווה","Petah Tikva"},
  {"פתחיה","Petahia"},
  {"צאלים","Tze'elim"},
  {"צבעון","Tziv'on"},
  {"צהלה","Tzahala"},
  {"צהלון ושיכוני חסכון","Tzahalon and Shikunei Hisachon"},
  {"צובה","Tzova"},
  {"צוחר","Tzohar"},
  {"צופים","Zufim"},
  {"צופית","Tzofit"},
  {"צופר","Tzofar"},
  {"צוקי אביב","Tzukei Aviv"},
  {"צוקי ים","Tzukei Yam"},
  {"צוקים","Tzukim"},
  {"צור הדסה","Tzur Hadassah"},
  {"צור יצחק","Tzur Yitzhak"},
  {"צור משה","Tzur Moshe"},
  {"צור נתן","Tzur Natan"},
  {"צור שלום","Tzur Shalom"},
  {"צוריאל","Tzuriel"},
  {"צורית","Tzurit"},
  {"צורן","Tsoran"},
  {"ציפורי","Tzipori"},
  {"צלפון","Tslafon"},
  {"צמרות איילון","Tsamarot Ayalon"},
  {"צנחנים","Tsanhanim"},
  {"צפון יפו","North Jaffa"},
  {"צפריה","Tzafria"},
  {"צפרירים","Tzafririm"},
  {"צפת","Safed"},
  {"צרופה","Tzrufa"},
  {"צרעה","Tsor'a"},
  {"קבועה","Kabu'a"},
  {"קבוצת יבנה","Kvutzat Yavne"},
  {"קבוצת כנרת","Kvutzat Kinneret"},
  {"קדומים","Kdumim"},
  {"קדימה","Kadima"},
  {"קדמה","Kedma"},
  {"קדמת צבי","Kidmat Tsvi"},
  {"קדמת ראשון","Kidmat Rishon"},
  {"קדרון","Kidron"},
  {"קדרים","Kadarim"},
  {"קומי אורי","Komi Uri"},
  {"קוממיות","Komemiyut"},
  {"קורנית","Koranit"},
  {"קטורה","Ketura"},
  {"קיבוץ מרחביה","Kibbuts Merhavia"},
  {"קידה","Kida"},
  {"קידר","Kedar"},
  {"קידר דרום","Kedar Darom"},
  {"קיסריה","Caesarea"},
  {"קיסריה","Caesarea"},
  {"קלחים","Klahim"},
  {"קליה","Kalya"},
  {"קלע אלון","Qela' Alon"},
  {"קציר","Katzir"},
  {"קצרין","Ketzrin"},
  {"קריית ביאליק","Kiryat Bialik"},
  {"קריית הלאום","Kiryat HaLeom"},
  {"קריית חרושת","Kiryat Haroshat"},
  {"קריית טבעון","Kiryat Tiv'on"},
  {"קריית טבעון","Kiryat Tiv'on"},
  {"קריית ים","Kiryat Yam"},
  {"קריית מוצקין","Kiryat Motzkin"},
  {"קריית נטפים","Kiryat Netafim"},
  {"קריית ענבים","Kiryat Anavim"},
  {"קרית אונו","Kiryat Ono"},
  {"קרית ארבע","Kiryat Arba"},
  {"קרית ארבע","Kiryat Arba"},
  {"קרית אתא","Kiryat Ata"},
  {"קרית גת","Kiryat Gat"},
  {"קרית חיים","Kiryat Haim"},
  {"קרית יערים","Kiryat Ye'arim"},
  {"קרית מלאכי","Kiryat Malakhi"},
  {"קרית עמל","Kiryat Amal"},
  {"קרית עקרון","Kiryat Ekron"},
  {"קרית קריניצי","Kiryat Krinitsi"},
  {"קרית שאול","Kiryat Shaul"},
  {"קרית שלום","Kiryat Shalom"},
  {"קרית שמונה","Qiryat Shemona"},
  {"קרני שומרון","Karnei Shomron"},
  {"קשכר נבארי","Qishkar Nabari"},
  {"קשת","Keshet"},
  {"ראס עלי","Ras Ali"},
  {"ראש הנקרה","Rosh HaNikra"},
  {"ראש העין","Rosh HaAyin"},
  {"ראש פינה","Rosh Pinna"},
  {"ראש צורים","Rosh Tzurim"},
  {"ראשון לציון","Rishon LeZion"},
  {"רבבה","Revava"},
  {"רבדים","Revdid"},
  {"רביבים","Revivim"},
  {"רביבים","Revivim"},
  {"רביד","Ravid"},
  {"רגבה","Regba"},
  {"רגבים","Regavim"},
  {"רווחה","Revaha"},
  {"רוויה","Revaya"},
  {"רוחמה","Ruhama"},
  {"רועי","Ro'i"},
  {"רותם","Rotem"},
  {"רחוב","Rehov"},
  {"רחובות","Rehelovot"},
  {"רחלים","Rehelim"},
  {"ריחן","Reihan"},
  {"ריינה","Reineh"},
  {"רימונים","Rimonim"},
  {"רינתיה","Rinatya"},
  {"רכסים","Rekhasim"},
  {"רם און","Ram-On"},
  {"רמות","Ramot"},
  {"רמות השבים","Ramot HaShavim"},
  {"רמות מאיר","Ramot Meir"},
  {"רמות מנשה","Ramot Menashe"},
  {"רמות נפתלי","Ramot Naftali"},
  {"רמלה","Ramla"},
  {"רמת אברהם","Ramat Avraham"},
  {"רמת אפעל","Ramat Efal"},
  {"רמת בית שמש א","Ramat Beit Shemesh A"},
  {"רמת בית שמש ב","Ramat Beit Shemesh B"},
  {"רמת גן","Ramat Gan"},
  {"רמת דוד","Ramat David"},
  {"רמת החייל","Ramat HaHayal"},
  {"רמת הטייסים","Ramat HaTayasim"},
  {"רמת הכובש","Ramat HaKovesh"},
  {"רמת השופט","Ramat HaShofet"},
  {"רמת השרון","Ramat HaSharon"},
  {"רמת חן","Ramat Hen"},
  {"רמת טראמפ","Ramat Trump"},
  {"רמת יוחנן","Ramat Yohanan"},
  {"רמת יצחק","Ramat Yitshak"},
  {"רמת ישי","Ramat Yishai"},
  {"רמת מגשימים","Ramat Magshimim"},
  {"רמת עמידר","Ramat Amidar"},
  {"רמת צבי","Ramat Tzvi"},
  {"רמת רזיאל","Ramat Raziel"},
  {"רמת רחל","Ramat Rachel"},
  {"רמת שקמה","Ramat Shikma"},
  {"רמת-אביב","Ramat-Aviv"},
  {"רנן","Ranen"},
  {"רעים","Re'im"},
  {"רעננה","Ra'anana"},
  {"רקפת","Rakefet"},
  {"רשפון","Rishpon"},
  {"רשפים","Reshafim"},
  {"רתמים","Retamim"},
  {"שאר ישוב","Rest of Settlement"},
  {"שבות רחל","Shvut Rahel"},
  {"שבי דרום","Shavei Darom"},
  {"שבי ציון","Shavei Tzion"},
  {"שבי שומרון","Shavei Shomron"},
  {"שדה אילן","Sde Ilan"},
  {"שדה אליהו","Sde Eliyahu"},
  {"שדה אליעזר","Sde Eliezer"},
  {"שדה בוקר","Sde Boker"},
  {"שדה דוד","Sde David"},
  {"שדה ורבורג","Sde Warburg"},
  {"שדה יואב","Sde Yoav"},
  {"שדה יעקב","Sde Ya'aqov"},
  {"שדה יצחק","Sde Yitzhak"},
  {"שדה משה","Sde Moshe"},
  {"שדה נחום","Sde Nahum"},
  {"שדה נחמיה","Sde Nehemia"},
  {"שדה ניצן","Sde Nitzan"},
  {"שדה עוזיהו","Sde Uziyahu"},
  {"שדה צבי","Sde Tzvi"},
  {"שדות ים","Sdot Yam"},
  {"שדות מיכה","Sdot Micha"},
  {"שדי אברהם","Sdei Avraham"},
  {"שדי חמד","Sdei Hemed"},
  {"שדי תרומות","Sdei Trumot"},
  {"שדמה","Shdema"},
  {"שדמות דבורה","Shadmot Dvora"},
  {"שדמות מחולה","Shadmot Mehola"},
  {"שדרות","Sderot"},
  {"שואבה","Sho'eva"},
  {"שובה","Shuva"},
  {"שובל","Shoval"},
  {"שוהם","Shoham"},
  {"שומרה","Shomera"},
  {"שומריה","Shomria"},
  {"שומרת","Shomrat"},
  {"שוקדה","Shokeda"},
  {"שורש","Shoresh"},
  {"שורשים","Shorashim"},
  {"שושנת העמקים","Shoshanat HaAmakim"},
  {"שזור","Shezor"},
  {"שחר","Shahar"},
  {"שחרות","Shaharut"},
  {"שילה","Shila"},
  {"שילת","Shilat"},
  {"שכונה ה","Shchuna E"},
  {"שכונה ו","Shchuna F"},
  {"שכונת החורש","Shchunat Hahoresh"},
  {"שכונת העמק","Shchunat HaEmek"},
  {"שכונת הרחבה","Shchunat Ha-Rakhava"},
  {"שכונת למד","Shchunat Lamd"},
  {"שכונת נאות גולף","Shchunat Neot Golf"},
  {"שכונת צמרות","Shchunat Tzamerot"},
  {"שכניה","Shekhanya"},
  {"שלהבת","Shalhevet"},
  {"שלהבת-יה","Shelvet-ya"},
  {"שלווה","Shalva"},
  {"שלוחות","Shluhot"},
  {"שלומי","Shlomi"},
  {"שמורת מאליבו","Shmurat Malibu"},
  {"שמיר","Shamir"},
  {"שמעה","Shim'a"},
  {"שמשית","Shimshit"},
  {"שני ליבנה","Shani Livne"},
  {"שניר","Snir"},
  {"שעל","Sha'al"},
  {"שעלבים","Sha'alvim"},
  {"שער אפרים","Sha'ar Efraim"},
  {"שער הגולן","Sha'ar HaGolan"},
  {"שער העמקים","Sha'ar HaAmakim"},
  {"שערי תקוה","Sha'arei Tikva"},
  {"שפיים","Shefayim"},
  {"שפיר","Shafir"},
  {"שפירא","Shapira"},
  {"שפר","Shefer"},
  {"שפרעם","Shfar'am"},
  {"שקד","Shaked"},
  {"שקף","Shekef"},
  {"שרונה","Sarona"},
  {"שריגים (לי־און)","Srigim (Li-On)"},
  {"שריד","Sarid"},
  {"שרשרת","Sharsheret"},
  {"שתולה","Shtula"},
  {"שתולים","Shtulim"},
  {"תאשור","Ta'ashur"},
  {"תדהר","Tidhar"},
  {"תובל","Tuval"},
  {"תומר","Tomer"},
  {"תושייה","Tushia"},
  {"תימורים","Timorim"},
  {"תירוש","Tirosh"},
  {"תל ברוך","Tel Baruch"},
  {"תל ברוך צפון","Tel Baruch Zafon"},
  {"תל גנים","Tel Ganim"},
  {"תל חיים","Tel Haim"},
  {"תל יוסף","Tel Yosef"},
  {"תל יצחק","Tel Yitzhak"},
  {"תל מונד","Tel Mond"},
  {"תל עדשים","Tel Adashim"},
  {"תל ציון","Tel Tsiyon"},
  {"תל קציר","Tel Kazir"},
  {"תל תאומים","Tel Te'omim"},
  {"תלם","Telem"},
  {"תלמי אליהו","Talmei Eliyahu"},
  {"תלמי אלעזר","Talmei Elazar"},
  {"תלמי ביל״ו","Talmei Bilu"},
  {"תלמי יוסף","Talmei Yosef"},
  {"תלמי יחיאל","Talmei Yehi'el"},
  {"תלמי יפה","Talmei Yaffe"},
  {"תלמים","Tlamim"},
  {"תמרת","Timrat"},
  {"תנובות","Tnuvot"},
  {"תעוז","Ta'oz"},
  {"תפרח","Tifrah"},
  {"תקומה","Tkuma"},
  {"תקומה","Tkuma"},
  {"תקוע","Tekoa"},
  {"תקוע","Tekoa"},
  {"תרום","Tarum"},
  {"أبو العسجا","Abu al-Asja"},
  {"أبو داهوك - تجمّع أبو ليمون - بيت إكسا","Abu Dahouk - Abu Limoun Gathering - Beit Iksa"},
  {"أبو ديس","Abu Dis"},
  {"أبو رقيق","Abu Raqiq"},
  {"أبو سريخان","Abu Srikhan"},
  {"أبو سلطان","Abu Sultan"},
  {"أبو سنان","Abu Sinan"},
  {"أبو عفش","Abu Afash"},
  {"أبو عمار","Abu Ammar"},
  {"أبو عيسى","Abu Issa"},
  {"أبو غوش‎","Abu Ghosh"},
  {"أبو قرينات","Abu Qureinat"},
  {"أريحا","Jericho"},
  {"أم السهلي","Umm al-Sahli"},
  {"أم الغنم","Umm al-Ghanam"},
  {"أم الفحم","Umm al-Fahm"},
  {"أم القطف","Umm al-Qatif"},
  {"أم بطين","Umm Batin"},
  {"أم لصفة","Umm Lasfa"},
  {"إبطن","Ibtin"},
  {"الإسكان الشرقي","Eastern Housing"},
  {"البعنة","Al-Ba'na"},
  {"البعينة","Al-Ba'ina"},
  {"البقعة","Al-Buqa'a"},
  {"البقيعة","Al-Buqa'a"},
  {"البقيعة","Al-Buwaib"},
  {"البويب","Al-Bayar"},
  {"البيار","Al-Jarjawi"},
  {"الجرجاوي","Al-Jish"},
  {"الجش","Al-Haram Al-Sharif"},
  {"الحرم القدسي الشريف","Al-Hafasi"},
  {"الحفاصي","Al-Hafasi"},
  {"الحفاصي","Al-Halqum"},
  {"الحَلْقوم","Al-Hamra"},
  {"الحمرة","New Eastern Neighborhood"},
  {"الحي الشرقي الجديد","Al-Dahi"},
  {"الدحي","Al-Danfiri"},
  {"الدنفيري","Al-Dirat"},
  {"الديرات","Al-Rama"},
  {"الرامة","Al-Rahaniyya"},
  {"الرحانية","Al-Rahma"},
  {"الرحمة","Al-Rihaniyya"},
  {"الريحانية","Al-Ziyadna"},
  {"الزيادنا الناصرة","Al-Nasirah"},
  {"السدرة","Al-Sidra"},
  {"السيد","Al-Sayyid"},
  {"السيد‎","Al-Sayyid"},
  {"الشبلي","Al-Shibli"},
  {"الشيخ دنون‎","Sheikh Danun"},
  {"الضاحية الجنوبية","Southern Suburb"},
  {"الضاحية الشمالية","Northern Suburb"},
  {"الضوا","Dawaa"},
  {"الضواحي الشرقية","Eastern Suburbs"},
  {"الطباخ","Al-Tabakh"},
  {"الطيبة الزعبية","Al-Tayyiba Al-Za'biya"},
  {"الطيرة","Al-Tira"},
  {"العرامشة","Al-Aramsha"},
  {"العريان","Al-Aryan"},
  {"العزير","Al-Uzair"},
  {"العساكرة","Al-Asakira"},
  {"العقبان","Al-Uqban"},
  {"الفرّاسين","Al-Farasin"},
  {"الفريديس","Al-Fureidis"},
  {"الفريديس","Al-Fureidis"},
  {"القرنة الشمالية","Northern Qurna"},
  {"القرينات وضاحية القندول","Al-Quraynat and Al-Qandoul Suburb"},
  {"الكرشان","Al-Karshan"},
  {"الكمانة الغربية","Al-Kamana Al-Gharbiya"},
  {"المجد","Al-Majd"},
  {"المذبح","Al-Madhbah"},
  {"المزرعة","Al-Mazra'a"},
  {"المزرعة","Al-Mazra'a"},
  {"المغار","Al-Maghar"},
  {"المقيبلة","Al-Muqaybila"},
  {"المُنْطَار","Al-Muntar"},
  {"المَنِيِّة","Al-Maniya"},
  {"الناعورة","Al-Na'ura"},
  {"الناقوره","Al-Naqura"},
  {"النواقير","Al-Nawaqir"},
  {"الهيب","Al-Hayb"},
  {"الوليدي","Al-Walidi"},
  {"بئر هداج","Bir Hadaj"},
  {"بد فلوح","Bad Faluh"},
  {"بٌدرُس","Badrus"},
  {"بدو الزّعيّم","Badu Al-Za'im"},
  {"بدو جبع شرق","Badu Jaba' Sharq"},
  {"بدو ضاحية الأقباط","Badu Dahiyat Al-Aqbat"},
  {"برقة","Burqa"},
  {"بسمة طبعون","Basmat Tab'un"},
  {"بقعاثا","Buqa'atha"},
  {"بياضة","Bayada"},
  {"بيت امرين","Bayt Amrin"},
  {"بيت جن","Bayt Jann"},
  {"بيت لحم","Bethlehem"},
  {"تجمع مليحات","Tajammu' Mleihat"},
  {"ترابين الصانع","Tarabin Al-Sana'"},
  {"تعنك","Ta'anak"},
  {"تقوع‎","Taqou'"},
  {"تل عراد","Tel Arad"},
  {"جبل الأقرع","Mount Aqra"},
  {"جت","Jatt"},
  {"جديدة-المكر","Jadida-Makr"},
  {"جناتة","Jannata"},
  {"جنين","Jenin"},
  {"جواميص","Jawamis"},
  {"جولس","Julis"},
  {"حارة الخولي (خربة كفر قرع)","Harat al-Khouli (Khirbet Kafr Qara)"},
  {"حجاجرة","Hajajra"},
  {"حرفيش","Harfish"},
  {"حرملة","Harmala"},
  {"حسينية","Husayniya"},
  {"حمام","Hammam"},
  {"حمدون","Hamdun"},
  {"حمصة التحتا","Hamsa al-Tahta"},
  {"حورة","Hura"},
  {"خَرائِب أمُّ اللَحْمْ","Khara'ib Umm al-Lahm"},
  {"خِرْبَةْ أبو عَنْقَر","Khirbet Abu Anqar"},
  {"خِرْبِة المَراجِم","Khirbet al-Marajim"},
  {"خربة بيت تعمر","Khirbet Beit Ta'mar"},
  {"خربة جمرين الأثرية","Khirbet Jamrin Archaeological Site"},
  {"خربة ربود ربيد","Khirbet Raboud Rabid"},
  {"خِرْبِة سَبْعِين","Khirbet Sab'in"},
  {"خِرْبِة صَرَّة","Khirbet Sarra"},
  {"خِرْبِة طَانَا","Khirbet Tana"},
  {"خربة طويّل - تَل الخَشَبَة","Khirbet Tawil - Tel al-Khashaba"},
  {"خربة عيون كفر قرع - حارة ال مقبل","Khirbet Ayoun Kafr Qara - Harat al-Muqbil"},
  {"خِرْبِة غْوين الفُوقَا","Khirbet Ghwein al-Fouqa"},
  {"خربة مسعود","Khirbet Mas'oud"},
  {"خلة اللوزة","Khallat al-Lawza"},
  {"خلة المية","Khallat al-Miya"},
  {"دالية الكرمل","Daliyat al-Karmel"},
  {"دبورية","Daburiyya"},
  {"دريجات","Drijat"},
  {"دورا القرع","Dura al-Qar'"},
  {"دير أبو الغزلان רבוד","Deir Abu al-Ghazlan"},
  {"دير الأسد","Deir al-Asad"},
  {"دير العسل التحتا","Deir al-Asal al-Tahta"},
  {"دير بريكة وضاحية الصوانة","Deir Breika and the al-Sawana suburb"},
  {"دير بلوط","Deir Ballut"},
  {"دير حنا","Deir Hanna"},
  {"‎‎دير شرف","Deir Sharaf"},
  {"رأس العين","Ras al-Ain"},
  {"رام الله","Ramallah"},
  {"رخمة","Rakhma"},
  {"رمانة","Rummana"},
  {"رمانة","Rummana"},
  {"رمة الهيب","Rummat al-Hayb"},
  {"روابي","Rawabi"},
  {"زرزير","Zarzir"},
  {"زعاترة الزعيَم - الزّانبا","Za'tara al-Za'im - al-Zanba"},
  {"زعتره‎","Za'tara"},
  {"زلفة","Zalfa"},
  {"ساجور","Sajur"},
  {"سالم","Salem"},
  {"سخنين","Sakhnin"},
  {"سعورا","Sa'ura"},
  {"سلامة‎","Salama"},
  {"سلفيت","Salfit"},
  {"سواعد حميرة","Sawa'id Hamira"},
  {"سولم","Sulam"},
  {"سيلة الحارثية","Silat al-Harithiya"},
  {"شبتين","Shabtin"},
  {"شعب‎","Sha'ab"},
  {"شقيب السلام","Shuqib al-Salam"},
  {"صندلة","Sandala"},
  {"ضاحية البستان","Dahiyat al-Bustan"},
  {"ضاحية الزيتون - الصوانة","Dahiyat al-Zaytoun - al-Sawana"},
  {"ضاحية الياسمين - أبو شوك","Dahiyat al-Yasmin - Abu Shouk"},
  {"ضحية","Dahia"},
  {"ضميدة","Dhamida"},
  {"طباش","Tabash"},
  {"طرابين الصانع","Tarabin al-Sana'"},
  {"طرعان","Tur'an"},
  {"طمرة‎","Tamra"},
  {"طوبا الزنغرية","Tuba al-Zangariyya"},
  {"طوبلاس","Tubas"},
  {"طولكرم","Tulkarm"},
  {"عبدة","Abda"},
  {"عبدة","Abda"},
  {"عرابة","Arraba"},
  {"عرب الرّماضين الشّمالي","Araba al-Ramadin al-Shamali"},
  {"عرب الكعابنة","Arab al-Ka'abna"},
  {"عرب المريسات","Arab al-Muraysat"},
  {"عرب النعيم","Arab al-Na'im"},
  {"عرب عصين","Arab 'Asin"},
  {"عرعرة","Ar'ara"},
  {"عرعرة النقب","Ar'ara an-Naqab"},
  {"عسفيا","Usfiya"},
  {"عصيره الشماليّه","Asira ash-Shamaliyya"},
  {"عقدة","Aqada"},
  {"عم سفا","Am Safa"},
  {"عوجان","Awjan"},
  {"عوقبي","Uqbi"},
  {"عيلبون","Ailaboun"},
  {"عيلوط","Aylut"},
  {"عين إبراهيم","Ein Ibrahim"},
  {"عين الأسد","Ein asad"},
  {"عين السهلة‎","Ein as-Sahla"},
  {"عين حوض","Ein Hawd"},
  {"عين قنية","Ein Qiniya"},
  {"عين كينيا","Ein Kenya"},
  {"فَخْتْ الجُول","Fakht al-Jul"},
  {"فسوطة","Fasuta"},
  {"فهيدات","Fahidat"},
  {"قبيا","Qibya"},
  {"قحاوش","Qahawish"},
  {"قديرات الصانع","Qudairat al-Sana'"},
  {"قرية تل الحمة","Tel al-Hamma Village"},
  {"قصر السر","Qasr al-Sir"},
  {"قطاع غزة","Gaza Strip"},
  {"قلنسوة","Qalansuwa"},
  {"قواعين","Qawa'in"},
  {"كحلة","Kahla"},
  {"كسرى","Kisra"},
  {"كسيفة","Kuseifa"},
  {"كعبية","Ka'abiyya"},
  {"كعبية الشمالية","Ka'abiyya al-Shamaliyya"},
  {"كعبية طباش حجاجرة","Ka'abiyya Tabash Hajajra"},
  {"كفر سميع","Kafr Sumei'"},
  {"كفر كما","Kafr Kama"},
  {"كفر مصر","Kafr Misr"},
  {"كفر مندا","Kafr Manda"},
  {"كفر ياسيف","Kafr Yasif"},
  {"كوكب أبو الهيجاء","Kawkab Abu al-Hija'"},
  {"لبونة","Lubuna"},
  {"ليفجِم","Lifjim"},
  {"مجد الكروم","Majd al-Krum"},
  {"مجدل شمس","Majdal Shams"},
  {"مزاريب","Mazareeb"},
  {"مسعدة","Mas'ada"},
  {"مشايح السعدية","Mashayeh al-Sa'diyya"},
  {"مشيرفة","Mushayrifa"},
  {"مصمص","Masmus"},
  {"معليا","Ma'ilya"},
  {"مكحول","Makhul"},
  {"منشية الزبدة","Manshiyat al-Zubda"},
  {"ميثلون","Mithlun"},
  {"ميسر","Maysar"},
  {"نابلس","Nablus"},
  {"نين","Nin"},
  {"هندازة","Hindaza"},
  {"هواشلة","Hawashla"},
  {"وادي أبو الصّوان","Wadi Abu al-Suwan"},
  {"وادي أريحا","Wadi Ariha"},
  {"وادي الأعوج","Wadi al-A'waj"},
  {"وادي القلط","Wadi al-Qalt"},
  {"وادي المشاش","Wadi al-Mashash"},
  {"وادي برقين","Wadi Burqin"},
  {"وادي شوباش","Wadi Shubash"},
  {"وادي قَانا","Wadi Qana"},
  {"وعر البيك","Wa'r al-Beik"},
  {"يانوح","Yanuh"},
  
  /* Towns added later*/
  {"תל אביב","Tel Aviv"},
  {"כרמיאל","Karmiel"},
  {"עפולה תחתית","Afula Tahtit"},

 };


const std::string AltNamesWords[NUM_ALT_NAME_BLOCKS][ALT_NAME_BLOCK_SIZE] =
 {
  {"Afek"      , "Afeq"       , "Afec"                                                                                                                  },
  {"Afeka"     , "Afeqa"      , "Afequa"                                                                                                                },
  {"Afeka"     , "Afeqa"      , "Afequa"      , "Afeca"                                                                                                 },
  {"Afik"      , "Afiq"       , "Afic"                                                                                                                  },
  {"Afikim"    , "Afiqim"     , "Afiquim"                                                                                                               },
  {"Akiva"     , "Aqiva"      , "Aquiva"                                                                                                                },
  {"Amakim"    , "Amaqim"     , "Amaquim"                                                                                                               },
  {"Amasa"     , "Amassa"                                                                                                                               },
  {"Amuka"     , "Amuqa"      , "Amuqua"                                                                                                                },
  {"Ashkelon"  , "Ashqelon"   , "Ashquelon"                                                                                                             },
  {"Baqa"      , "Baqua"      , "Baka"                                                                                                                  },
  {"Barak"     , "Baraq"                                                                                                                                },
  {"Barkai"    , "Barqai"     , "Barquai"                                                                                                               },
  {"Barkan"    , "Barqan"     , "Barquan"                                                                                                               },
  {"Barkat"    , "Barqat"     , "Barquat"     , "Bareket"     , "Bareqet"      , "Barequet"                                                             },
  {"Batzra"    , "Batsra"     , "Bazra"                                                                                                                 },
  {"Benei"     , "Beney"      , "Bnei"        , "Bney"        , "Bne"          , "Bne"                                                                  },
  {"Beqa"      , "Bequa"      , "Beka"                                                                                                                  },
  {"Beqaot"    , "Bequaot"    , "Bekaot"                                                                                                                },
  {"Beqat"     , "Bequat"     , "Bekat"                                                                                                                 },
  {"Beqoa"     , "Bequoa"     , "Bekoa"                                                                                                                 },
  {"Bialik"    , "Bialiq"                                                                                                                               },
  {"Binyamin"  , "Benyamin"   , "Binjamin"    , "Benjamin"                                                                                              },
  {"Binyamina" , "Benyamina"  , "Binjamina"   , "Benjamina"                                                                                             },
  {"Boker"     , "Boqer"      , "Boquer"                                                                                                                },
  {"Brak"      , "Braq"                                                                                                                                 },
  {"Brakha"    , "Bracha"     , "Braha"                                                                                                                 },
  {"Brukhin"   , "Bruchin"    , "Bruhin"      , "Brokhin"     , "Brochin"      , "Brohin"                                                               },
  {"Carmel"    , "Karmel"                                                                                                                               },
  {"Cohen"     , "Kohen"      , "Kogan"       , "Cogan"                                                                                                 },
  {"Dekalim"   , "Deqalim"    , "Dequalim"                                                                                                              },
  {"Dekalim"   , "Deqalim"    , "Dequalim"    , "Dkalim"      , "Dqalim"       , "Dqualim"                                                              },
  {"Dekel"     , "Deqel"      , "Dequel"                                                                                                                },
  {"Dimona"    , "Demona"                                                                                                                               },
  {"Dishon"    , "Deshon"                                                                                                                               },
  {"Dkalim"    , "Dqalim"     , "Dqualim"                                                                                                               },
  {"Eliakim"   , "Eliaqim"    , "Eliaquim"                                                                                                              },
  {"Eliyau"    , "Eliyahu"                                                                                                                              },
  {"Elkana"    , "Elqana"     , "Elquana"     , "Elcana"                                                                                                },
  {"Elkosh"    , "Elaqosh"    , "Elaquosh"    , "Elacosh"                                                                                               },
  {"Emek"      , "Emeq"                                                                                                                                 },
  {"Eshkol"    , "Eshqol"     , "Eshquol"                                                                                                               },
  {"Eshkolot"  , "Eshqolot"   , "Eshquolot"   , "Eshcolot"                                                                                              },
  {"Gedera"    , "Guedera"    , "Gadera"      , "Guadera"                                                                                               },
  {"Gefen"     , "Guefen"                                                                                                                               },
  {"Geulei"    , "Gueulei"                                                                                                                              },
  {"Gezer"     , "Guezer"                                                                                                                               },
  {"Gidon"     , "Guidon"                                                                                                                               },
  {"Gidona"    , "Guidona"                                                                                                                              },
  {"Ginaton"   , "Guinaton"                                                                                                                             },
  {"Ginegar"   , "Guinegar"                                                                                                                             },
  {"Ginosar"   , "Guinosar"   , "Ginossar"    , "Guinossar"                                                                                             },
  {"Giora"     , "Geora"      , "Guiora"      , "Gueora"                                                                                                },
  {"Gitit"     , "Guitit"                                                                                                                               },
  {"Hadassah"  , "Hadasah"    , "Hadassa"     , "Hadasa"                                                                                                },
  {"Halutz"    , "Haluz"      , "Haluts"                                                                                                                },
  {"Havatzelet", "Havazelet"  , "Havatselet"                                                                                                            },
  {"Hen"       , "Chen"                                                                                                                                 },
  {"Herzliya"  , "Hertzliya"  , "Hertsliya"   , "Herzlia"     , "Hertzlia"      , "Hertslia"                                                            },
  {"Hilkia"    , "Hilqia"     , "Hilquia"                                                                                                               },
  {"Jerusalem" , "Yirushalaim", "Yerushalaim" , "Yirushalaiim", "Yerushalaiim"  , "Yirushalayim" , "Yerushalayim"                                       },
  {"Kadarim"   , "Qadarim"    , "Quadarim"    , "Cadarim"                                                                                               },
  {"Kadima"    , "Qadima"     , "Quadima"                                                                                                               },
  {"Kama"      , "Qama"       , "Quama"                                                                                                                 },
  {"Karmel"    , "Carmel"                                                                                                                               },
  {"Karmiel"   , "Carmiel"                                                                                                                              },
  {"Karmiel"   , "Carmiel"                                                                                                                              },
  {"Karmit"    , "Karmit"                                                                                                                               },
  {"Karnei"    , "Qarnei"     , "Quarnei"     , "Carnei"                                                                                                },
  {"Kazir"     , "Katzir"     , "Katsir"      , "Qazir"       , "Qatzir"        , "Qatsir"      ,  "Quazir"    , "Quatzir"   , "Quatsir"                },
  {"Kdumim"    , "Qdumim"     , "Kedumim"     , "Qedumim"     , "Quedumim"                                                                              },
  {"Kedima"    , "Qedima"     , "Quedima"                                                                                                               },
  {"Kedma"     , "Qedma"      , "Quedma"                                                                                                                },
  {"Kedmat"    , "Qedmat"     , "Quedmat"                                                                                                               },
  {"Keshet"    , "Qeshet"     , "Queshet"                                                                                                               },
  {"Khawaled"  , "Chawaled"   , "Hawaled"                                                                                                               },
  {"Kibbuts"   , "Qibbuts"    , "Quibbuts"    , "Kibbutz"     , "Qibbutz"       , "Quibbutz"    , "Kibbuz"     , "Qibbuz"    , "Quibbuz"                },
  {"Kidron"    , "Qidron"     , "Quidron"     , "Kedron"      , "Qedron"        , "Quedron"                                                             },
  {"Kiryat"    , "Qiryat"     , "Quiryat"     , "Kiriyat"     , "Qiriyat"       , "Quiriyat"    , "Kiriat"     , "Qiriat"    , "Quiriat"                },
  {"Komemiyut" , "Qomemiyut"  , "Komemiut"    , "Qomemiut"    , "Kumemiyut"     , "Qumemiyut"   , "Kumemiut"   , "Qumemiut"  , "Quomemiyut", "Quomemiut"},
  {"Kvutzat"   , "Kvutsat"    , "Kvutsat"     , "Qvutzat"     , "Qvutsat"       , "Qvutsat"                                                             },
  {"Kvutzat"   , "Kvuzat"     , "Kvutsat"     , "Qvutzat"     , "Qvuzat"        , "Qvutsat"                                                             },
  {"Kvutzot"   , "Kvuzot"     , "Kvutsot"     , "Qvutzot"     , "Qvuzot"        , "Qvutsot"                                                             },
  {"Lachish"   , "Lakhish"    , "Lahish"                                                                                                                },
  {"Lahav"     , "Laav"                                                                                                                                 },
  {"Lahavim"   , "Laavim"     , "Lehavim"     , "Leavim"                                                                                                },
  {"Maccabim"  , "Makkabim"   , "Macabim"     , "Makabim"                                                                                               },
  {"Massad"    , "Masad"                                                                                                                                },
  {"Massada"   , "Masada"                                                                                                                               },
  {"Menachem"  , "Menahem"                                                                                                                              },
  {"Mevoot"    , "Mevohot"    , "Mavoot"      , "Mavohot"                                                                                               },
  {"Migdal"    , "Megdal"                                                                                                                               },
  {"Mikha"     , "Micha"      , "Miha"                                                                                                                  }, 
  {"Mishmar"   , "Meshmar"                                                                                                                              },
  {"Mitzpe"    , "Mizpe"      , "Mitspe"                                                                                                                },
  {"Modiin"    , "Modiyin"                                                                                                                              },
  {"Monosson"  , "Monoson"                                                                                                                              },
  {"Motza"     , "Moza"       , "Motsa"                                                                                                                 },
  {"Motzkin"   , "Motskin"    , "Mozkin"      , "Motzqin"     , "Motsqin"       , "Mozqin"       , "Motzquin"   , "Motsquin"  , "Mozquin"               },
  {"Naqquba"   , "Neqquba"    , "Nakkuba"     , "Nekkuba"     , "Naccuba"       , "Neccuba"      , "Nacquba"    , "Necquba"   , "Nackuba"   , "Neckuba" },
  {"Nekofa"    , "Neqofa"     , "Nequofa"                                                                                                               },
  {"Nikra"     , "Niqra"      , "Nekra"       , "Neqra"       , "Nikrah"        , "Niqrah"       , "Nekrah"     , "Neqrah"                              },
  {"Nitzan"    , "Nizan"      , "Nitsan"                                                                                                                },
  {"Ofakim"    , "Ofaqim"     , "Ofaquim"                                                                                                               },
  {"Ofek"      , "Ofaq"                                                                                                                                 },
  {"Petah"     , "Petakh"     , "Petach"                                                                                                                },
  {"Pinna"     , "Pina"                                                                                                                                 },
  {"Qishkar"   , "Quishkar"   , "Kishkar"                                                                                                               },
  {"Quedem"    , "Qedem"      , "Kedem"                                                                                                                 },
  {"Rahel"     , "Rachel"                                                                                                                               },
  {"Rakefet"   , "Raqefet"    , "Raquefet"                                                                                                              },
  {"Safed"     , "Tsfat"      , "Tzfat"       , "Zfat"                                                                                                  },
  {"Sde"       , "Sade"       , "Sdeh"        , "Sadeh"                                                                                                 },
  {"Shaked"    , "Shaqed"     , "Shaqued"                                                                                                               },
  {"Shefayim"  , "Shfayim"                                                                                                                              },
  {"Shekhanya" , "Shechanya"  , "Shehanya"                                                                                                              },
  {"Shezor"    , "Shesor"                                                                                                                               },
  {"Shikma"    , "Shiqma"                                                                                                                               },
  {"Shluhot"   , "Shluchot"                                                                                                                             },
  {"Sikha"     , "Sicha"      , "Siha"                                                                                                                  },
  {"Sikora"    , "Siqora"     , "Siquora"                                                                                                               },
  {"Sorek"     , "Soreq"      , "Sorec"                                                                                                                 },
  {"Teiman"    , "Taiman"     , "Teyman"      , "Tayman"                                                                                                },
  {"Tekoa"     , "Teqoa"      , "Tequoa"                                                                                                                },
  {"Tikva"     , "Tikwa"      , "Tiqva"       , "Tiqwa"       , "Tiqua"                                                                                 },
  {"Tquma"     , "Tequma"     , "Tkuma"       , "Tekuma"                                                                                                },
  {"Tserada"   , "Tzerada"    , "Zerada"                                                                                                                },
  {"Tslafon"   , "Tzlafon"    , "Zlafon"                                                                                                                },
  {"Tsuran"    , "Tzuran"     , "Zuran"       , "Tsoran"      , "Tzoran"        ,"Zoran"                                                                },
  {"Tzafria"   , "Tsafria"    , "Zafria"                                                                                                                },
  {"Tzafririm" , "Tsafririm"  , "Zafririm"                                                                                                              },
  {"Tzipori"   , "Zipori"     , "Tsipori"                                                                                                               },
  {"Tzova"     , "Zova"       , "Tsova"                                                                                                                 },
  {"Tzrufa"    , "Tsrufa"     , "Zrufa"                                                                                                                 },
  {"Yaakov"    , "Yaaqov"     , "Yakov"       , "Yaqov"                                                                                                 },
  {"Yagel"     , "Yaguel"                                                                                                                               },
  {"Yakhini"   , "Yachini"    , "Yahini"                                                                                                                },
  {"Yakir"     , "Yaqir"      , "Yaquir"                                                                                                                },
  {"Yakum"     , "Yaqum"                                                                                                                                },
  {"Yarkon"    , "Yarqon"     , "Yarquon"                                                                                                               },
  {"Yarkona"   , "Yarqona"    , "Yarquona"                                                                                                              },
  {"Yarok"     , "Yaroq"                                                                                                                                },
  {"Yehud"     , "Yeud"       , "Iehud"       , "Ieud"        , "Ihud"          , "Iud"                                                                 },
  {"Yehuda"    , "Yeuda"      , "Iehuda"      , "Ieuda"       , "Ihuda"         , "Iuda"                                                                },
  {"Yericho"   , "Yeriho"                                                                                                                               },
  {"Yesodot"   , "Yessodot"                                                                                                                             },
  {"Yesud"     , "Yessud"     , "Yesod"       , "Yessod"                                                                                                },
  {"Yitshak"   , "Yitzhak"    , "Yizhak"      , "Yitshaq"     , "Yitzhaq"       , "Yizhaq"                                                              },
  {"Yitshar"   , "Yitzhar"    , "Yizhar"                                                                                                                },
  {"Yohai"     , "Yuhai"                                                                                                                                },
  {"Yosef"     , "Yossef"     , "Josef"                                                                                                                 },
  {"Zekharia"  , "Zecharia"   , "Zeharia"                                                                                                               },
  {"Zikhron"   , "Zichron"    , "Zihron"                                                                                                                },
  {"Zikim"     , "Ziqim"      , "Ziquim"                                                                                                                },
  {"Zimra"     , "Tzimra"     , "Tsimra"                                                                                                                },
  {"Zion"      , "Tzion"      , "Tsion"                                                                                                                 },
  {"Zofar"     , "Tzofar"     , "Tsofar"                                                                                                                },
  {"Zofit"     , "Tzofit"     , "Tsofit"                                                                                                                },
  {"Zova"      , "Tzova"      , "Tsova"                                                                                                                 },
  {"Zrufa"     , "Tzrufa"     , "Tsrufa"                                                                                                                },
  {"Zukei"     , "Tzukei"     , "Tsukei"                                                                                                                },
  {"Zukim"     , "Tzukim"     , "Tsukim"                                                                                                                },
  {"Zur"       , "Tzur"       , "Zur"                                                                                                                   },
  {"Zurim"     , "Tzurim"     , "Tsurim"                                                                                                                },
  {"Zvi"       , "Tzvi"       , "Tsvi"                                                                                                                  },


 };